/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";
import SecurityFeatureItem from "./SecurityFeatureItem";
import { securityFeatures } from "./securityFeaturesData";
import { LOGOS_URL_MAP } from "@/constants/AssetConstants";
import { MAX_WIDTH_MEDIA_SCREENS, WINDOW_SIZE } from "@/Themes/Device";

interface SecurityFeaturesProps {
  className?: string;
}

const SecurityFeatures: React.FC<SecurityFeaturesProps> = ({ className }) => {
  return (
    <SecurityFeaturesContainer>
      <ContentWrapper>
        <Header>
          <Title className="title">Your security. Our priority.</Title>
          <Partnership>
            <PartnershipText className="partnership-text">
              In partnership with
            </PartnershipText>
            <PartnerLogo
              className="partner-logo"
              src={LOGOS_URL_MAP.FI_FEDERAL}
              alt="Partner logo"
              loading="lazy"
            />
          </Partnership>
        </Header>
        <FeaturesList className="features-list">
          {securityFeatures.map((feature, index) => (
            <SecurityFeatureItem key={index} {...feature} />
          ))}
        </FeaturesList>
      </ContentWrapper>
    </SecurityFeaturesContainer>
  );
};

const SecurityFeaturesContainer = styled.section`
  display: flex;
  margin-top: 32px;
  align-items: center;
  width: 100%;
  justify-content: space-between;
  max-width: 1130px;

  @media (${MAX_WIDTH_MEDIA_SCREENS.tab}) {
    max-width: 80%;
  }

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    max-width: 100%;
    padding: 0 8%;
    flex-direction: column;
  }

  @media (max-width: ${WINDOW_SIZE.PHONE}px) {
    padding: 0 5%;
  }
`;

const ContentWrapper = styled.div`
  display: flex;
  width: 100%;
  gap: 100px;
  justify-content: space-between;

  @media (${MAX_WIDTH_MEDIA_SCREENS.tab}) {
    gap: 50px;
  }

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    flex-direction: column;
    gap: 30px;
  }
`;

const Header = styled.header`
  align-self: stretch;
  display: flex;
  flex-direction: column;
  justify-content: start;
  margin: auto 0;

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    text-align: center;
    width: 100%;
  }
`;

const Title = styled.h1`
  color: #333;
  font: 500 55px/50px Gilroy, sans-serif;

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    max-width: 100%;
    font-family: Gilroy;
    font-size: 1.8rem;
    font-weight: 600;
    line-height: 2rem;
    text-align: center;
  }

  @media (max-width: ${WINDOW_SIZE.PHONE}px) {
    font-size: 30px;
    line-height: 35px;
  }
`;

const Partnership = styled.div`
  display: flex;
  margin-top: 20px;
  height: 40px;
  width: 100%;
  align-items: center;
  gap: 8px;
  color: #6a6d70;
  text-align: center;
  justify-content: flex-start;
  font: 400 22px/30px Inter, sans-serif;

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    justify-content: center;
    margin-top: 0;
    font-size: 18px;
    line-height: 26px;
    gap: 10px;
    font-weight: 500;
    text-align: center;
  }

  @media (max-width: ${WINDOW_SIZE.PHONE}px) {
    font-size: 16px;
    line-height: 24px;
  }
`;

const PartnershipText = styled.p`
  font-feature-settings: "liga" off, "clig" off;
  align-self: stretch;
  margin: auto 0;

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    font-family: Inter;
    font-size: 0.8rem;
    font-weight: 400;
    line-height: 1rem;
    text-align: right;
  }
`;

const PartnerLogo = styled.img`
  aspect-ratio: 3.97;
  object-fit: contain;
  object-position: center;
  width: 123px;
  align-self: stretch;
  margin: auto 0;

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    text-align: left;
    object-position: left;
    padding: 7px 0;
    margin: 0;
  }

`;

const FeaturesList = styled.main`
  align-self: stretch;
  display: flex;
  flex-direction: column;
  overflow: hidden;
  color: #313234;
  justify-content: center;
  margin: auto 0;
  padding: 16px 0;
  font: 600 24px/32px Gilroy, sans-serif;

  @media (${MAX_WIDTH_MEDIA_SCREENS.tab}) {
    font-size: 20px;
    line-height: 28px;
  }

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    font-size: 18px;
    line-height: 26px;
    padding: 0;
    padding-right: 20px;
  }

  @media (max-width: ${WINDOW_SIZE.PHONE}px) {
    font-size: 16px;
    line-height: 24px;
  }
`;

export default SecurityFeatures;
