/**
 * This code was generated by Builder.io.
 */
import { MAX_WIDTH_MEDIA_SCREENS, WINDOW_SIZE } from "@/Themes/Device";
import React from "react";
import styled from "styled-components";

interface SecurityFeatureItemProps {
  iconSrc: string;
  description: string;
}

const SecurityFeatureItem: React.FC<SecurityFeatureItemProps> = ({
  iconSrc,
  description,
}) => {
  return (
    <StyledSecurityFeatureItem>
      <FeatureIconWrapper>
        <FeatureIcon src={iconSrc} alt="Security feature icon" loading="lazy" />
      </FeatureIconWrapper>

      <FeatureDescription>{description}</FeatureDescription>
    </StyledSecurityFeatureItem>
  );
};

const StyledSecurityFeatureItem = styled.div`
  display: flex;
  width: 100%;
  align-items: center;
  gap: 21px;
  justify-content: start;
  margin-top: 12px;

  @media (${MAX_WIDTH_MEDIA_SCREENS.tab}) {
    gap: 10px;
  }
`;

const FeatureIconWrapper = styled.div`
  min-width: 64px;
  min-height: 64px;
  border-radius: 200%;
  display: flex;
  justify-content: center;
  align-items: center;

  @media (${MAX_WIDTH_MEDIA_SCREENS.tab}) {
    min-width: 50px;
    min-height: 50px;
  }

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    min-width: 40px;
    min-height: 40px;
  }

  @media (max-width: ${WINDOW_SIZE.PHONE}px) {
    min-width: 32px;
    min-height: 32px;
  }
`;

const FeatureIcon = styled.img`
  aspect-ratio: 1;
  object-fit: contain;
  object-position: center;
  width: 24px;

  @media (${MAX_WIDTH_MEDIA_SCREENS.tab}) {
    width: 20px;
  }

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    width: 18px;
  }

  @media (max-width: ${WINDOW_SIZE.PHONE}px) {
    width: 16px;
  }
`;

const FeatureDescription = styled.p`
  font-feature-settings: "liga" off, "clig" off;
  margin: auto 0;

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    font-family: Gilroy;
    font-size: 0.8rem;
    font-weight: 500;
    line-height: 1rem;
    text-align: left;
    color:#646464;

  }
`;

export default SecurityFeatureItem;
