import { DEBIT_CARD_IMG_URL_MAP } from "@/constants/AssetConstants";

/**
 * This code was generated by Builder.io.
 */
export const securityFeatures = [
  {
    iconSrc: DEBIT_CARD_IMG_URL_MAP.THUMBS_UP_ICON,
    description: "Your money is secured up to ₹5L",
  },
  {
    iconSrc: DEBIT_CARD_IMG_URL_MAP.GEAR_ICON,
    description: "Set limits for purchases, freeze and unfreeze card, and do more with a few taps",
  },
  {
    iconSrc: DEBIT_CARD_IMG_URL_MAP.SHIELD_ICON,
    description: "Fi offers end-to-end protection. Your data is always safe with us",
  },
  {
    iconSrc: DEBIT_CARD_IMG_URL_MAP.TICK_ICON,
    description: "Fi-Federal Debit Card is issued by Federal Bank in Partnership with Fi-Brand Limited.",
  },
];
