/**
 * This code was generated by Builder.io.
 */
import { MAX_WIDTH_MEDIA_SCREENS, WINDOW_SIZE } from "@/Themes/Device";
import React from "react";
import styled from "styled-components";

const CardHeader: React.FC = () => {
  return (
    <Header>
      <Title>The Fi-Federal Debit Card</Title>
      <Subtitle>Your Ultimate Travel Companion</Subtitle>
    </Header>
  );
};

const Header = styled.header`
  align-items: center;
  background: var(--Background-Dark-Base, #18191b);
  display: flex;
  width: 100%;
  flex-direction: column;
  font-family: Gilroy, sans-serif;
  text-align: center;
  justify-content: flex-start;
  @media (${MAX_WIDTH_MEDIA_SCREENS.tab}) {
    max-width: 100%;
    text-align: left;
    align-items: flex-start;
  }
`;

const Title = styled.h1`
  color: var(--snow-fffff, #fff);
  font-size: 90px;
  font-weight: 500;
  line-height: 1;
  @media (${MAX_WIDTH_MEDIA_SCREENS.tab}) {
    max-width: 100%;
    font-size: 70px;
    font-weight: 600;
  }
  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    font-size: 2.5rem;
    font-weight: 550;
  }

  @media (max-width: ${WINDOW_SIZE.PHONE}px) {
    font-size: 40px;
    font-weight: 600;
  }
`;

const Subtitle = styled.h2`
  color: var(--Content-On-Light-Medium-Emphasis-600, #6a6d70);
  font-feature-settings: "liga" off, "clig" off;
  font-size: 40px;
  font-weight: 600;
  line-height: 1;
  margin-top: 12px;

  @media (${MAX_WIDTH_MEDIA_SCREENS.tab}) {
    max-width: 100%;
    font-size: 30px;
  }

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    font-size: 1rem;
    font-family: Gilroy;
    font-weight: 500;
    line-height: 1.4rem;
    text-align: left;
  }

  @media (max-width: ${WINDOW_SIZE.PHONE}px) {
    font-size: 18px;
    font-family: Gilroy;
    font-weight: 500;
    line-height: 1.4rem;
    text-align: left;
  }
`;

export default CardHeader;
