/**
 * This code was generated by Builder.io.
 */
import React, { useEffect, useState } from 'react';

import CardHeader from './CardHeader';
import IssuedBy from './IssuedBy';
import CardImage from './CardImage';
import { CardBody, CardContent, Dot, Dots, TravelCardWrapper } from './styles';
import Benefits from './Benfits';

interface TravelCardProps {

  setCtaText: React.Dispatch<React.SetStateAction<string>>;

}

const TravelCard: React.FC<TravelCardProps> = ({ setCtaText }) => {
  const [isInternational, setIsInternational] = useState(true);

  useEffect(() => {
    setCtaText('Get the ZERO forex card');
  }, [])

  useEffect(() => {
    if (isInternational) {
      setCtaText('Get the ZERO forex card');
    } else {
      setCtaText('Get the Debit Card');
    }
  }, [isInternational]);

  return (
    <TravelCardWrapper>
      <CardContent>
        <CardHeader />
        <CardBody>
          <Benefits isInternational={isInternational} setIsInternational={setIsInternational} />
          <Dots>
            <Dot isActive={isInternational} />
            <Dot isActive={!isInternational} />
          </Dots>
          <CardImage />
          <IssuedBy />
        </CardBody>
      </CardContent>
    </TravelCardWrapper>
  );
};

export default TravelCard;
