const GET_FAQ_DATA = 'FAQ/GET_FAQ_DATA';
const UPDATE_FAQ_DATA = 'FAQ/UPDATE_FAQ_DATA';
const GET_CATEGORIES_DATA = 'FAQ/GET_CATEGORIES_DATA';
const UPDATE_CATEGORIES_DATA = 'FAQ/UPDATE_CATEGORIES_DATA';
const GET_FOLDERS_AND_ARTICLES_FOR_CATEGORY = 'FAQ/GET_FOLDERS_AND_ARTICLES_FOR_CATEGORY';
const UPDATE_FOLDERS_AND_ARTICLES_FOR_CATEGORY = 'FAQ/UPDATE_FOLDERS_AND_ARTICLES_FOR_CATEGORY';
const GET_RELATED_FAQS_DATA = 'FAQ/GET_RELATED_FAQS_DATA';
const UPDATE_RELATED_FAQS_DATA = 'FAQ/UPDATE_RELATED_FAQS_DATA';
const GET_ACTIVE_FOLDER_INDEX = 'FAQ/GET_ACTIVE_FOLDER_INDEX';

const trackingPayload = {
    flow_name: 'website',
    channel: 'website',
    page_name: 'faqs page',
};

export {
    GET_FAQ_DATA,
    UPDATE_FAQ_DATA,
    GET_CATEGORIES_DATA,
    UPDATE_CATEGORIES_DATA,
    GET_FOLDERS_AND_ARTICLES_FOR_CATEGORY,
    UPDATE_FOLDERS_AND_ARTICLES_FOR_CATEGORY,
    GET_RELATED_FAQS_DATA,
    UPDATE_RELATED_FAQS_DATA,
    GET_ACTIVE_FOLDER_INDEX,
    trackingPayload,
};
