/**
 * This code was generated by Builder.io.
 */
import { MAX_WIDTH_MEDIA_SCREENS } from "@/Themes/Device";
import React from "react";
import styled from "styled-components";
import { ToggleButton, ToggleWrapper } from "../styles";

type BenefitsToggleProps = {
  isInternational: boolean;
  setIsInternational: React.Dispatch<React.SetStateAction<boolean>>;
};

const BenefitsToggle: React.FC<BenefitsToggleProps> = ({ isInternational, setIsInternational }) => {
  return (
    <ToggleWrapper position={ isInternational ? 'left' : 'right'}>
      <ToggleButton isActive={isInternational} onClick={() => setIsInternational(!isInternational)}>International benefits</ToggleButton>
      <ToggleButton isActive={!isInternational} onClick={() => setIsInternational(!isInternational)}>Domestic benefits</ToggleButton>
    </ToggleWrapper>
  );
};

export default BenefitsToggle;
