export const GET_EMAIL_VERIFY_STATUS = 'CUSTOMERAUTH/GET_EMAIL_VERIFY_STATUS';
export const UPDATE_EMAIL_VERIFY_STATUS = 'CUSTOMERAUTH/UPDATE_EMAIL_VERIFY_STATUS';
export const GET_NAME_BY_USER_ID = 'CUSTOMERAUTH/GET_NAME_BY_USER_ID';
