/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";
import PartnerLogos from "./PartnerLogos";
import { MAX_WIDTH_MEDIA_SCREENS, WINDOW_SIZE } from "@/Themes/Device";

interface SecurityPartnersProps {}

const SecurityPartners: React.FC<SecurityPartnersProps> = () => {
  return (
    <SecurityPartnersContainer>
      <ContentWrapper>
        <TextColumn>
          <Title>Fi partners with the best to secure your money</Title>
          <PartnerLogos />
        </TextColumn>
        <InfoColumn>
          <Description>
            Our partner bank hosts your Savings Account and follows all security standards per applicable regulations.
            <br />
            <br />
            Your money is always safe with our banking partner - Federal Bank and
            your money is covered under the Deposit Insurance and Credit Guarantee Corporation Scheme.
            This insures your money up to <Highlight>₹5 lakh</Highlight>.
            <br />
            <br />
            Fi itself is not a bank and doesn't hold or claim to have a banking license.
          </Description>
        </InfoColumn>
      </ContentWrapper>
    </SecurityPartnersContainer>
  );
};

export default SecurityPartners;

const SecurityPartnersContainer = styled.section`
  display: flex;
  flex-direction: row;
  max-width: 1130px;
  width: 100%;
  padding-top: 40px;

  @media (${MAX_WIDTH_MEDIA_SCREENS.tab}) {
    max-width: 80%;
  }

  @media (max-width: ${WINDOW_SIZE.PHONE}px) {
    padding: 0 50px;
    max-width: 100%;
  }
`;

const ContentWrapper = styled.div`
  display: flex;
  gap: 100px;

  @media (${MAX_WIDTH_MEDIA_SCREENS.tab}) {
    flex-direction: column;
    align-items: stretch;
    gap: 40px;
  }
`;

const TextColumn = styled.div`
  display: flex;
  flex-direction: column;
  line-height: normal;
  width: 50%;
  margin-left: 0;
  @media (${MAX_WIDTH_MEDIA_SCREENS.tab}) {
    width: 100%;
    gap: 20px;
  }
`;

const Title = styled.h2`
  color: #333;
  font: 600 50px/1 Gilroy, sans-serif;
  margin-top: -15px;

  @media (${MAX_WIDTH_MEDIA_SCREENS.tab}) {
    max-width: 100%;
    text-align: center;
  }

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    font-family: Gilroy;
    font-size: 30px;
    font-weight: 600;
    line-height: 36px;
    text-align: center;
  }

  @media (max-width: ${WINDOW_SIZE.PHONE}px) {
    font-size: 30px;
    line-height: 33px;
  }
`;

const InfoColumn = styled.div`
  display: flex;
  flex-direction: column;
  line-height: normal;
  width: 50%;

  @media (${MAX_WIDTH_MEDIA_SCREENS.tab}) {
    width: 100%;
    text-align: center;
  }
`;

const Description = styled.p`
  color: #8d8d8d;
  align-self: stretch;
  margin: auto 0;
  font: 500 20px/24px Inter, sans-serif;

  @media (${MAX_WIDTH_MEDIA_SCREENS.tab}) {
    max-width: 100%;
  }

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    font-size: 12px;
    font-weight: 500;
    line-height: 16px;
    text-align: center;
  }

  @media (max-width: ${WINDOW_SIZE.PHONE}px) {
    font-size: 14px;
    line-height: 18px;
  }
`;

const Highlight = styled.span`
  font-weight: 700;
  color: #8d8d8d;
`;
