/**
 * This code was generated by Builder.io.
 */
import { Font } from "@/Abstract";
import { Device, MAX_WIDTH_MEDIA_SCREENS, WINDOW_SIZE } from "@/Themes/Device";
import MIXINS from "@/Themes/mixins";
import { LOGOS_URL_MAP } from "@/constants/AssetConstants";
import React from "react";
import styled from "styled-components";

interface PartnerLogo {
  src?: string;
  alt?: string;
  width?: number;
  aspectRatio?: number;
  text?: string;
}

const partnerLogos: PartnerLogo[] = [
  {
    src: LOGOS_URL_MAP.FEDERAL,
    alt: "Federal Bank Logo",
    width: 112,
    aspectRatio: 1.87,
  },
  {
    src: LOGOS_URL_MAP.VISA,
    alt: "Visa Logo",
    width: 72,
    aspectRatio: 1.2,
  },
  {
    src: LOGOS_URL_MAP.NPCI,
    alt: "NPCI Logo",
    width: 85,
    aspectRatio: 1.42,
  },
  {
    src: LOGOS_URL_MAP.FI_PCI,
    alt: "PCI Logo",
    width: 75,
    aspectRatio: 1.25,
  },
  {
    src: LOGOS_URL_MAP.EPIFI_WEALTH,
    alt: "Epifi Wealth Logo",
    width: 112,
    aspectRatio: 1.883,
  },
  {
    text: "ISO 27001:2013",
  }
];

const PartnerLogos: React.FC = () => {
  return (
    <LogoContainer>
      {partnerLogos.map((logo, index) => (
        logo.text ? <Text tagType='text' font='p5VariantOne' color='CHARCOAL_GREY'>{logo.text}</Text> : (
          <Logo
            key={index}
            src={logo.src}
            alt={logo.alt}
            width={logo.width}
            aspectRatio={logo.aspectRatio}
          />
        )
      ))}
    </LogoContainer>
  );
};

export default PartnerLogos;

const LogoContainer = styled.div`
  display: flex;
  align-items: center;
  gap: 20px;
  justify-content: start;
  flex-wrap: wrap;

  @media (${MAX_WIDTH_MEDIA_SCREENS.tab}) {
    align-items: center;
    justify-content: center;
  }
`;

const Logo = styled.img<{ aspectRatio?: number }>`
  aspect-ratio: ${(props) => props.aspectRatio};
  object-fit: contain;
  object-position: center;
  width: ${(props) => props.width}px;

  @media (${MAX_WIDTH_MEDIA_SCREENS.tab}) {
    width: ${(props) => (props.width as number * 5) / 6}px;
  }

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    width: ${(props) => (props.width as number * 2) / 3}px;
  }

  @media (max-width: ${WINDOW_SIZE.PHONE}px) {
    width: ${(props) => (props.width as number) / 2}px;
  }
`;

const Text = styled(Font)`
  white-space: nowrap;
  ${MIXINS.FontMixin({
      weight: 700, size: '14px', lineHeight: '120%', font: 'Inter',
  })};

  @media ${Device.tab} {
      ${MIXINS.FontMixin({
          weight: 700, size: '16px', lineHeight: '120%', font: 'Inter',
      })};
  }


  @media ${Device.desktop} {
      ${MIXINS.FontMixin({
          weight: 700, size: '20px', lineHeight: '120%', font: 'Inter',
      })}; 
  }
`;
