/**
 * This code was generated by Builder.io.
 */
import { MAX_WIDTH_MEDIA_SCREENS, WINDOW_SIZE } from "@/Themes/Device";
import React from "react";
import styled from "styled-components";

const DescriptionWrapper = styled.div`
  display: flex;
  min-width: 240px;
  flex-direction: column;
  font-weight: 500;
  justify-content: start;
  width: 50%;
  margin: auto 0;
  @media (${MAX_WIDTH_MEDIA_SCREENS.tab}) {
    width: 60%;
  }
  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    width: 100%;
    padding: 0 40px;
    justify-content: center;
    text-align: center;
  }
`;

const TextContent = styled.div`
  display: flex;
  width: 100%;
  flex-direction: column;
  justify-content: start;
`;

const Title = styled.h2`
  color: rgba(51, 51, 51, 1);
  font: 48px/50px Gilroy, sans-serif;
  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    max-width: 100%;
    font-size: 1.8rem;
    line-height: 2rem;
    font-weight: 600;
  }

  @media (max-width: ${WINDOW_SIZE.PHONE}px) {
    font-size: 30px;
    line-height: 30px;
  }
`;

const Subtitle = styled.p`
  color: var(--slate-8-d-8-d-8-d, #8d8d8d);
  margin-top: 20px;
  font: 24px/34px Inter, sans-serif;

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    font-size: 1rem;
    line-height: 1.4rem;
    font-weight: 500;
  }

  @media (max-width: ${WINDOW_SIZE.PHONE}px) {
    font-size: 18px;
    line-height: 20px;
  }
`;

export const FeatureDescription: React.FC = () => {
  return (
    <DescriptionWrapper>
      <TextContent>
        <Title>Works like magic anywhere, everywhere</Title>
        <Subtitle>
          Works seamlessly however you want to use it across 180+ countries
        </Subtitle>
      </TextContent>
    </DescriptionWrapper>
  );
};
