/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";
import { FeatureDescription } from "./FeatureDescription";
import { PaymentMethodCarousel } from "./PaymentMethodCarousel";
import { MAX_WIDTH_MEDIA_SCREENS } from "@/Themes/Device";

const FeatureContainer = styled.section`
  display: flex;
  width: 100%;
  max-width: 1130px;
  align-items: center;
  gap: 100px;
  justify-content: space-between;

  @media (${MAX_WIDTH_MEDIA_SCREENS.tab}) {
    max-width: 80%;
    gap: 50px;
  }
  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    flex-direction: column;
    gap: 30px;
    max-width: 100%;
  }
`;

const MagicPaymentFeature: React.FC = () => {
  return (
    <FeatureContainer>
      <FeatureDescription />
      <PaymentMethodCarousel />
    </FeatureContainer>
  );
};

export default MagicPaymentFeature;
