/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";

import { DEBIT_CARD_IMG_URL_MAP } from "@/constants/AssetConstants";
import { MAX_WIDTH_MEDIA_SCREENS, WINDOW_SIZE } from "@/Themes/Device";
import { Carousel as CarouselContainer, LeftArrow, RightArrow } from "@/components";

const CarouselWrapper = styled.div`
  display: flex;
  min-width: 240px;
  flex-direction: column;
  overflow: hidden;
  width: 50%;
  height: 400px;
  margin: auto 0;
  @media (${MAX_WIDTH_MEDIA_SCREENS.tab}) {
    width: 40%;
    height: 300px;
  }
  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    width: 100%;
    height: 230px;
  }

  @media (max-width: ${WINDOW_SIZE.PHONE}px) {
    height: 250px;
  }
`;

const Carousel = styled(CarouselContainer)`
  height: 100%;
  & > div:first-child {
    height: 100%;
`;

const PaymentImageWrapper = styled.div`
    display: flex;
    gap: 20px;
    height: 100%;
    @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
      gap: 30px;
      padding: 0 30px;
    }
`;

const PaymentImage = styled.img`
  border-radius: 40px;
  height: 100%;
  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
     border-radius: 10px;
     height: 100%;
  }
`;

const paymentMethods = [
  {
    src: DEBIT_CARD_IMG_URL_MAP.DEBIT_CARD_PAYMENT,
    alt: "Swipe or Tap-to-Pay",
  },
  {
    src: DEBIT_CARD_IMG_URL_MAP.CASH_CARD,
    alt: "Payment method 1",
  },
  {
    src: DEBIT_CARD_IMG_URL_MAP.ONLINE_PAYMENT,
    alt: "Payment method 3",
  },
];

export const PaymentMethodCarousel: React.FC = () => {
  return (
    <CarouselWrapper>
      <Carousel
          leftArrow={<LeftArrow />}
          rightArrow={<RightArrow />}
          leftScrollValue={document.getElementById('payment-image')?.offsetWidth || 400}
          rightScrollValue={document.getElementById('payment-image')?.offsetWidth || 400}
      >
        <PaymentImageWrapper>
          {paymentMethods.map((method, index) => (
            <PaymentImage  src={method.src} id='payment-image'/> 
          ))}
        </PaymentImageWrapper>
      </Carousel>
    </CarouselWrapper>
  );
};
