/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";
import ResearchCard from "./ResearchCard";
import { BlogData } from "../index";
import { MAX_WIDTH_MEDIA_SCREENS, WINDOW_SIZE } from "@/Themes/Device";

interface ResearchHelpProps {
  blogsData: Array<BlogData>;
}

const ResearchHelp: React.FC<ResearchHelpProps> = ({ blogsData }) => {
  return (
    <ResearchHelpContainer>
      <Header>Need help with research? Start here</Header>
      <CardContainer>
        {blogsData.map((blog, index) => (
          <ResearchCard key={index} {...blog} />
        ))}
      </CardContainer>
    </ResearchHelpContainer>
  );
};

const ResearchHelpContainer = styled.section`
  display: flex;
  flex-direction: column;
  max-width: 1130px;
  width: 100%;
  gap: 60px;

  @media (${MAX_WIDTH_MEDIA_SCREENS.tab}) {
    padding: 0 10%;
  }

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    padding: 0 8%;
    margin-top: 40px;
    gap: 40px;
  }
`;

const Header = styled.header`
  display: flex;
  justify-content: center;
  width: 100%;
  max-width: 875px;
  margin: 0 auto;
  color: #333;
  text-align: center;
  font: 500 48px/1 Gilroy, sans-serif;

  @media (${MAX_WIDTH_MEDIA_SCREENS.tab}) {
    font-size: 40px;
  }

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    max-width: 100%;
    padding: 0 20px;
    font-family: Gilroy;
    font-size: 1.9rem;
    font-weight: 600;
    line-height: 2.2rem;
    text-align: center;
  }

  @media (max-width: ${WINDOW_SIZE.PHONE}px) {
    font-size: 30px;
    font-weight: 700;
  }
`;

const CardContainer = styled.div`
  display: flex;
  gap: 20px;

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    flex-direction: column;
    align-items: stretch;
    gap: 30px;
  }
`;

export default ResearchHelp;
