/**
 * This code was generated by Builder.io.
 */
import { MAX_WIDTH_MEDIA_SCREENS, WINDOW_SIZE } from "@/Themes/Device";
import Link from "next/link";
import React from "react";
import styled from "styled-components";

interface ResearchCardProps {
  headerImage: string;
  category: string;
  categorySlug: string;
  title: string;
  readingDuration: string;
  slug: string;
}

const makeBlogUrl = (categorySlug: any, blogNameSlug: any) => {
  return `${window.location.origin}/guides/${categorySlug}/${blogNameSlug}`;
};

const ResearchCard: React.FC<ResearchCardProps> = ({
  headerImage,
  category,
  categorySlug,
  title,
  readingDuration,
  slug,
}) => {
  return (
    <Card href={makeBlogUrl(categorySlug, slug)} target="_blank">
      <CardImage src={headerImage} alt="" />
      <CardContent>
        <CardCategory>{category}</CardCategory>
        <Divider />
        <CardTitle>{title}</CardTitle>
        <CardReadTime>{readingDuration} min read</CardReadTime>
      </CardContent>
    </Card>
  );
};

const Card = styled(Link)`
  border-radius: 16px;
  background-color: #fff;
  display: flex;
  flex-direction: column;
  color: #333;
  font: 16px Gilroy, sans-serif;
  flex: 1;

  @media (${MAX_WIDTH_MEDIA_SCREENS.tab}) {
    font-size: 14px;
  }

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    font-size: 13px;
  }

  @media (max-width: ${WINDOW_SIZE.PHONE}px) {
    font-size: 10px;
  }
`;

const CardImage = styled.img`
  object-fit: contain;
  width: 100%;
  border-radius: 16px 16px 0 0;
`;

const CardContent = styled.div`
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  padding: 24px;
  height: 100%;

  @media (${MAX_WIDTH_MEDIA_SCREENS.tab}) {
    padding: 20px;
  }

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    padding: 18px;
  }

  @media (max-width: ${WINDOW_SIZE.PHONE}px) {
    padding: 14px;
  }
`;

const CardCategory = styled.span`
  font-weight: 700;
  line-height: 1.1;
  letter-spacing: 0.45px;
  text-transform: uppercase;
`;

const Divider = styled.hr`
  background-color: #c0dae0;
  margin: 8px 0;
  width: 42px;
  height: 2px;
  border: none;
`;

const CardTitle = styled.h2`
  font-size: 30px;
  font-weight: 600;
  line-height: 35px;
  margin: 10px 0;

  @media (${MAX_WIDTH_MEDIA_SCREENS.tab}) {
    font-size: 20px;
    line-height: 25px;
    font-weight: 650;
  }

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    font-family: Gilroy;
    font-size: 22px;
    font-weight: 400;
    line-height: 28.8px;
    text-align: left;
  }

  @media (max-width: ${WINDOW_SIZE.PHONE}px) {
    font-size: 16px;
    line-height: 20px;
    font-weight: 550;
  }
`;

const CardReadTime = styled.span`
  color: #a4a4a4;
  font-family: Inter, sans-serif;
  font-weight: 500;
  line-height: 1.4;
  margin-top: 20px;
  height: 100%;
  display: flex;
  flex-direction: column;
  justify-content: flex-end;

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    font-family: Inter;
    font-size: 12px;
    font-weight: 500;
    line-height: 16.8px;
    text-align: center;
    margin-top: 10px;
  }
`;

export default ResearchCard;
