/**
 * This code was generated by Builder.io.
 */
import { MAX_WIDTH_MEDIA_SCREENS } from "@/Themes/Device";
import { DEBIT_CARD_IMG_URL_MAP } from "@/constants/AssetConstants";
import React from "react";
import styled from "styled-components";

export const ForexSavingsCard: React.FC = () => {
  return (
    <CardContainer>
      <CardContent>
        <SavingsHighlight>
          <SavingsIcon
            loading="lazy"
            src={DEBIT_CARD_IMG_URL_MAP.STAR_WITHOUT_BG}
            alt="star"
          />
          <SavingsText>
            <strong>For every ₹1L spent, you save min. ₹4,100</strong>
          </SavingsText>
        </SavingsHighlight>
        <SavingsDescription>
          Typically, Debit/Credit Cards/Forex Cards charge forex fees of 3-5% on international spends. It’s waived off* for Fi-Federal Debit Card.
        </SavingsDescription>
        <Disclaimer>*Applicable on select plans</Disclaimer>
      </CardContent>
    </CardContainer>
  );
};

const CardContainer = styled.div`
  border-radius: 20px;
  background-color: #e9f7f4;
  display: flex;
  margin-top: 32px;
  width: 100%;
  overflow: hidden;
  padding: 20px;
  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    max-width: 100%;
    margin: 0;
    padding: 20px 40px;
    background-color: unset;
  }
`;

const CardContent = styled.div`
  display: flex;
  width: 469px;
  max-width: 100%;
  flex-direction: column;
  justify-content: start;
  font-family: 'Inter';
`;

const SavingsHighlight = styled.div`
  display: flex;
  width: 100%;
  align-items: center;
  gap: 4px;
  font-size: 18px;
  color: #004e2d;
  line-height: 1;
  justify-content: start;
  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    font-size: 16px;
  }
`;

const SavingsIcon = styled.img`
  aspect-ratio: 1;
  object-fit: contain;
  object-position: center;
  width: 24px;
  align-self: stretch;
  margin: auto 0;
  padding: 3px;
`;

const SavingsText = styled.p`
  font-feature-settings: "liga" off, "clig" off;
  align-self: stretch;
  margin: auto 0;
`;

const SavingsDescription = styled.p`
  color: #004e2d;
  font-feature-settings: "liga" off, "clig" off;
  font-size: 16px;
  line-height: 20px;
  margin-top: 12px;
  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    max-width: 100%;
    font-size: 14px;
  }
`;

const Disclaimer = styled.p`
  color: #6bcdb6;
  font-feature-settings: "liga" off, "clig" off;
  font-size: 12px;
  line-height: 1;
  margin-top: 12px;
  @media (max-width: 991px) {
    max-width: 100%;
  }
`;
