/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";
import { ForexSavingsCard } from "./ForexSavingsCard";
import { MAX_WIDTH_MEDIA_SCREENS } from "@/Themes/Device";
import { DEBIT_CARD_IMG_URL_MAP } from "@/constants/AssetConstants";

const ForexFeatures: React.FC = () => {
  return (
    <Container>
      <ContentWrapper>
        <Heading>Say bye to Forex fees*</Heading>
        <Subheading>
          <strong>Save up to 5%</strong> on every international spend, even ATM
          withdrawals!
        </Subheading>
      </ContentWrapper>
      <ImagePlaceholder src={DEBIT_CARD_IMG_URL_MAP.GLOBE_COINS_FULL} />
      <ForexSavingsCard />
    </Container>
  );
};

const Container = styled.section`
  display: grid;
  margin: 0 50px;
  max-width: 1130px;
  align-items: center;
  justify-content: space-between;
  grid-template-columns: 50% 1fr;
  column-gap: 100px;
  width: 100%;
  @media (${MAX_WIDTH_MEDIA_SCREENS.tab}) {
    column-gap: 50px;
    max-width: 80%;
  }
  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    max-width: 100%;
    margin: 0;
    padding: 0 20px;
    grid-template-columns: 100%;
    background: linear-gradient(180deg, #ffffff 0%, #e0f4f0 100%);
  }
`;

const ContentWrapper = styled.div`
  align-self: stretch;
  display: flex;
  min-width: 240px;
  flex-direction: column;
  justify-content: start;
  margin: auto 0;
  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    max-width: 100%;
    align-items: center;
    text-align: center;
  }
`;

const Heading = styled.h2`
  color: #333;
  font: 48px/1 Gilroy, sans-serif;
  font-weight: 500;
  @media (max-width: 991px) {
    max-width: 100%;
    font-size: 35px;
    font-weight: 700;
  }

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    font-family: Gilroy;
    font-size: 28px;
    font-weight: 600;
    line-height: 32px;
    text-align: center;
  }
`;

const Subheading = styled.p`
  color: #8d8d8d;
  margin-top: 20px;
  font: 24px/34px Inter, sans-serif;
  font-weight: 500;
  @media (max-width: 991px) {
    max-width: 100%;
    font-size: 20px;
  }

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    font-family: Inter;
    font-size: 16px;
    font-weight: 400;
    line-height: 24.8px;
    text-align: center;
    padding: 0 10px;
    color: #646464;

  }
`;

const ImagePlaceholder = styled.img`
  align-self: stretch;
  display: flex;
  min-width: 240px;
  height: 388px;
  margin: auto;
  grid-column: 2 / 3;
  grid-row: 1 / 3;
  width: auto;
  @media (max-width: 1100px) {
    width: 100%;
    height: auto;
  }

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    grid-column: unset;
    grid-row: unset;
    max-width: 100%;
    width: auto;
    height: 388px;
  }

  @media (max-width: 450px) {
    width: 100%;
    height: auto;
  }
`;

export default ForexFeatures;
