export const FINITE_CODE_TRACKING_PAYLOAD = {
    flow_name: 'waitlist',
    channel: 'finite code',
    page_name: 'finite code page',
};

export const ABOUT_PAGE_TRACKING_PAYLOAD = {
    flow_name: 'waitlist',
    channel: 'website',
    page_name: 'about page',
};

export const FAQS_PAGE_TRACKING_PAYLOAD = {
    flow_name: 'waitlist',
    channel: 'website',
    page_name: 'faqs page',
};

export const CAREERS_PAGE_TRACKING_PAYLOAD = {
    flow_name: 'waitlist',
    channel: 'website',
    page_name: 'careers page',
};

export const CALCULATORS_PAGE_TRACKING_PAYLOAD = {
    flow_name: 'website',
    channel: 'website',
    page_name: 'calculators page',
};

export enum creditCardEvents {
    LANDED_ON_INTRO_SCREEN = 'LANDED_ON_INTRO_SCREEN',
    SCROLL_ON_INTRO_SCREEN = 'SCROLL_ON_INTRO_SCREEN',
    CLICKED_CHECK_ELIGIBILITY_INTRO_SCREEN = 'CLICKED_CHECK_ELIGIBILITY_INTRO_SCREEN',
    LANDED_ON_MOBILE_SCREEN = 'LANDED_ON_MOBILE_SCREEN',
    CLICKED_VERIFY_MOBILE_NUMBER_SCREEN= 'CLICKED_VERIFY_MOBILE_NUMBER_SCREEN',
    LANDED_ON_OTP_SCREEN= 'LANDED_ON_OTP_SCREEN',
    ENTERED_OTP_WLCC= 'ENTERED_OTP_WLCC',
    VERIFY_OTP_WLCC= 'VERIFY_OTP_WLCC',
    LANDED_ON_PERSONAL_DETAILS= 'LANDED_ON_PERSONAL_DETAILS',
    ENTERED_FIRST_NAME_WLCC= 'ENTERED_FIRST_NAME_WLCC',
    ENTERED_LAST_NAME_WLCC= 'ENTERED_LAST_NAME_WLCC',
    ENTER_WORK_EMAIL_WLCC= 'ENTER_WORK_EMAIL_WLCC',
    ENTERED_PAN_WLCC= 'ENTERED_PAN_WLCC',
    ENTERED_DOB_WLCC= 'ENTERED_DOB_WLCC',
    CLICKED_ON_CONSENT_1_TICK_MARK_WLCC= 'CLICKED_ON_CONSENT_1_TICK_MARK_WLCC',
    CLICKED_ON_CONSENT_2_TICK_MARK_WLCC= 'CLICKED_ON_CONSENT_2_TICK_MARK_WLCC',
    CLICKED_CHECK_ELIGIBILITY_BUTTON_ON_DETAILS_PAGE= 'CLICKED_CHECK_ELIGIBILITY_BUTTON_ON_DETAILS_PAGE',
    'ELIGIBILITY_SUCCESS'= 'ELIGIBILITY_SUCCESS',
    'ELIGIBILITY_FAILURE'= 'ELIGIBILITY_FAILURE',
    'ELIGIBILITY_DOWNLOAD'= 'ELIGIBILITY_DOWNLOAD',
    'NON_ELIGIBILITY_DOWNLOAD'= 'Non-NON_ELIGIBILITY_DOWNLOAD'
}
