/**
 * This code was generated by Builder.io.
 */
import { MAX_WIDTH_MEDIA_SCREENS, WINDOW_SIZE } from "@/Themes/Device";
import { DropDown } from "@/components";
import React, { useState } from "react";
import styled from "styled-components";
import Config from './data.json';
import { IDropDown } from "@/components/DropDownVariantOne";
import { amountFormatter } from "../utils";

const formatCurrency = (obj: IDropDown): IDropDown => ({
  ...obj,
  label: amountFormatter((obj.label || 0) as number, {}, true)
});
const formatCurrencyOptions = (options: IDropDown[]): IDropDown[] => options.map((option) => formatCurrency(option));

interface BudgetInputProps {
  budget: IDropDown;
  setBudget: (value: IDropDown) => void;
}

export const BudgetInput: React.FC<BudgetInputProps> = ({ budget, setBudget }) => {
  const [isModalOpen, setIsModalOpen] = useState(false);
  return (
    <InputWrapper>
      <Label htmlFor="budget">What's your budget?</Label>
      <CustomDropDown
          value={budget}
          options={formatCurrencyOptions(Config?.budget)}
          handleInputChange={setBudget}
          hasDropDownWithSearch={true}
          setIsModalOpen={setIsModalOpen}
          isModalOpen={isModalOpen}
          hasMobileDesignV1={false}
          placeholder="Select"
      />
    </InputWrapper>
  );
};

const CustomDropDown = styled(DropDown)`
  & > div:first-child {
    background-color: #ffffff;
    border-radius: 90.037px;
    font-size: 24px;
    padding: 15px 20px;
    margin: 0px;

    @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
      display: flex;
      flex-direction: row;
      padding: 12px 20px;
      gap: 8px;
      font-size: 1rem;
      line-height: 1.2rem;
      font-weight: 700;
    }

    @media (max-width: ${WINDOW_SIZE.PHONE}px) {
      font-size: 16px;
      padding: 10px 15px;
    }
  }
  & > div:nth-child(2) {
    background-color: #FFFFFF;
    box-shadow: 0px 12px 15px rgba(0, 0, 0, 0.15), 0px 19px 30px rgba(0, 0, 0, 0.1), 0px 7px 30px rgba(0, 0, 0, 0.08);
    border-radius: 8px;
    font-size: 24px;
    line-height: 29px;
    min-width: 150%;
    max-width: 320px;
    top: 60px;
    right: 0px;
    position: absolute;

    @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
      font-size: 1rem;
      font-weight: 700;
      line-height: 1.2rem;
      text-align: center;
    }
  }
`;

const InputWrapper = styled.div`
  display: flex;
  width: 100%;
  align-items: center;
  gap: 24px;
  justify-content: start;
`;

const Label = styled.label`
  color: var(--Supporting-Jade-700, #007a56);
  font: 600 30px/1 Gilroy, sans-serif;
  flex-grow: 1;
  width: 324px;
  margin: auto 0;

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    font-size: 1rem;
    line-height: 1.2rem;
  }

  @media (max-width: ${WINDOW_SIZE.PHONE}px) {
    font-size: 20px;
    width: 100px;
  }
`;
