/**
 * This code was generated by Builder.io.
 */
import React, { useState } from "react";
import styled from "styled-components";
import { BudgetInput } from "./BudgetInput";
import { DestinationInput } from "./DestinationInput";
import { SavingsBreakdown } from "./SavingsBreakdown";
import { IDropDown } from "@/components/DropDownVariantOne";
import { DEBIT_CARD_IMG_URL_MAP } from "@/constants/AssetConstants";
import { MAX_WIDTH_MEDIA_SCREENS, WINDOW_SIZE } from "@/Themes/Device";

export const TravelSavings: React.FC = () => {
  const [destination, setDestination] = useState<IDropDown>({
    id: 1,
    label: "Thailand",
    value: "Thailand",
  });
  const [budget, setBudget] = useState<IDropDown>({
    id: 1,
    label: "₹1,00,000",
    value: "100000",
  });

  return (
    <TravelSavingsWrapper>
      <Header>TRAVELLING ABROAD?</Header>
      <SubHeader>
        <Title />
        <Subtitle>with a Fi-Federal Debit Card</Subtitle>
      </SubHeader>
      <ContentWrapper>
        <CardBackground
          loading="lazy"
          src={DEBIT_CARD_IMG_URL_MAP.MONEY_SAVED}
          alt=""
        />
        <InputsAndBreakdown>
          <InputsWrapper>
            <DestinationInput
              destination={destination}
              setDestination={setDestination}
            />
            <BudgetInput budget={budget} setBudget={setBudget} />
          </InputsWrapper>
          <SavingsBreakdown destination={destination} budget={budget} />
        </InputsAndBreakdown>
      </ContentWrapper>
      <Footer>
        <div>*T&C Apply. These values are indicative.</div>
        <div>**Applicable on select Fi Plans only.</div>
      </Footer>
    </TravelSavingsWrapper>
  );
};

const TravelSavingsWrapper = styled.section`
  display: flex;
  width: 100%;
  max-width: 1130px;
  flex-direction: column;
  @media (${MAX_WIDTH_MEDIA_SCREENS.tab}) {
    width: 80%;
  }
`;

const Header = styled.h1`
  color: var(--Neutrals-Lead-600, #6a6d70);
  text-align: center;
  font: 600 20px/0.8 Gilroy, sans-serif;
  letter-spacing: 0.5px;
  align-self: center;

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    font-family: Gilroy;
    font-size: 0.9rem;
    font-weight: 600;
    line-height: 1rem;
    letter-spacing: 0.5px;
    text-align: center;
    padding-bottom: 0;
  }

  @media (max-width: ${WINDOW_SIZE.PHONE}px) {
    font-size: 16px;
  }
`;

const SubHeader = styled.div`
  display: flex;
  margin-top: 16px;
  width: 100%;
  flex-direction: column;
  font-weight: 500;
  text-align: center;

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
     margin: 16px 0;
  }
`;

const Title = styled.h2`
  color: rgba(51, 51, 51, 1);
  font: 48px/1 Gilroy, sans-serif;

  &::before {
    content: "Looks like we have a winner";

    @media (${MAX_WIDTH_MEDIA_SCREENS.tab}) {
      content: "See how much you'll save";
    }

    @media (max-width: ${WINDOW_SIZE.PHONE}px) {
      font-size: 35px;
      font-weight: 600;
    }
  }

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    content: "See how much you'll save";
    font-weight: 600;
    font-size: 2rem;
    padding: 0 40px;
    margin-top: 1px;
  }
`;

const Subtitle = styled.p`
  color: var(--Content-On-Light-High-Emphasis-850, #313234);
  margin-top: 8px;
  font: 24px/1.4 Inter, sans-serif;

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    font-size: 1rem;
    font-weight: 500;
    line-height: 1.2rem;
  }

  @media (max-width: ${WINDOW_SIZE.PHONE}px) {
    font-size: 18px;
  }
`;

const ContentWrapper = styled.div`
  display: flex;
  margin-top: 68px;
  align-items: center;
  gap: 50px;
  justify-content: space-between;

  @media (${MAX_WIDTH_MEDIA_SCREENS.medium}) {
    gap: 100px;
  }

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    margin-top: 28px;
  }

  @media (${MAX_WIDTH_MEDIA_SCREENS.tab}) {
    gap: 15px;
    flex-direction: column-reverse;
  }
`;

const InputsAndBreakdown = styled.div`
  align-self: stretch;
  display: flex;
  min-width: 240px;
  flex-direction: column;
  justify-content: start;
  width: 50%;

  @media (${MAX_WIDTH_MEDIA_SCREENS.tab}) {
    width: 100%;
  }
`;

const InputsWrapper = styled.div`
  display: flex;
  width: 100%;
  gap: 30px;
  flex-direction: column;
  justify-content: start;
`;

const Footer = styled.footer`
  color: var(--Supporting-Jade-200, #6bcdb6);
  text-align: center;
  font: 500 12px/1 Inter, sans-serif;
  margin-top: 16px;
  align-self: start;
  display: flex;

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {

    gap: 10px;
    > div {
      font-size: 10px;
    }
  }

  @media (${MAX_WIDTH_MEDIA_SCREENS.tab}) {
    text-align: center;
    width: 100%;
    font-size: 20px;
    flex-direction: column;
    gap: 20px;
  }

  @media (max-width: ${WINDOW_SIZE.PHONE}px) {
    font-size: 12px;
    line-height: 0.8;
  }
`;

const CardBackground = styled.img`
  height: 100%;
  width: 50%;
  object-fit: cover;
  object-position: center;

  @media (${MAX_WIDTH_MEDIA_SCREENS.tab}) {
    width: 100%;
    content: url(${DEBIT_CARD_IMG_URL_MAP.MONEY_SAVED_MOBILE});
  }
`;
