import { NAVIGATION_URLS } from '@/constants/AppConstant';

export const PATH_MAP = {
    CREDIT_CARD_WAITLIST_SIGNUP: `${NAVIGATION_URLS.CREDIT_CARD_WAITLIST.url}/signup`,
    CREDIT_CARD_WAITLIST_ELIGIBILITY: `${NAVIGATION_URLS.CREDIT_CARD_WAITLIST.url}/eligibility`,
    SALARY_ACCOUNT_B2B: `${NAVIGATION_URLS.SALARY_ACCOUNT.url}/corporate`,
};
