/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";
import { BenefitDescription, BenefitIcon, BenefitItem, BenefitsWrapper } from "../styles";
import { DEBIT_CARD_IMG_URL_MAP } from "@/constants/AssetConstants";

interface BenefitProps {
  icon: string;
  nationalDescription: string;
  internationalDescription: string;
}

interface BenefitComponentProps {
  isInternational: boolean;
  benefit: BenefitProps;
}

const Benefit: React.FC<BenefitComponentProps> = ({ benefit: {icon, nationalDescription, internationalDescription}, isInternational }) => (
  <BenefitItem>
    <BenefitIcon src={icon} alt="" />
    <BenefitDescription>
      {
        isInternational ? internationalDescription : nationalDescription
      }
    </BenefitDescription>
  </BenefitItem>
);

const benefits: BenefitProps[] = [
  {
    icon: DEBIT_CARD_IMG_URL_MAP.GLOBE_ICON,
    internationalDescription: "Zero Forex fees* in 180+ countries",
    nationalDescription: "2% cashback* on all spends",
  },
  {
    icon: DEBIT_CARD_IMG_URL_MAP.WIFI_ICON,
    internationalDescription: "ATM withdrawals with zero Forex fees*",
    nationalDescription: "Free ATM withdrawals*",
  },
  {
    icon: DEBIT_CARD_IMG_URL_MAP.OFFERS_ICON,
    internationalDescription: "Big offers on Flights, Hotels, Cabs & more",
    nationalDescription: "Big Offers on EaseMyTrip, Yatra, LifeStyle, etc.",
  },
  {
    icon: DEBIT_CARD_IMG_URL_MAP.LOGIN_ICON,
    internationalDescription: "Auto-Pay for international subscriptions",
    nationalDescription: "Tap & Pay anywhere",
  },
];

const BenefitsList: React.FC<{ isInternational: boolean }> = ({ isInternational }) => {
  return (
    <BenefitsWrapper>
      {benefits.map((benefit, index) => (
        <Benefit
          key={index}
          benefit={benefit}
          isInternational={isInternational}
        />
      ))}
    </BenefitsWrapper>
  );
};

export default BenefitsList;
