/**
 * @file USStockCollection Constants
 */

const DEFAULT_SELECTED_SORT_OPTION = { title: 'SORT BY DEFAULT', type: 'SORT_OPTION_TYPE_RELEVANCY' };

export {
    // eslint-disable-next-line import/prefer-default-export
    DEFAULT_SELECTED_SORT_OPTION,
};

// ActionNames Enum
export enum ActionNames {
    GET_US_STOCKS_COLLECTION_DETAILS_ACTION = 'GET_US_STOCKS_COLLECTION_DETAILS',
}

// Component key
export const US_STOCKS_KEY = 'USStocks';

// Actions
export const GET_US_STOCKS_DETAILS = `app/${US_STOCKS_KEY}/GET_US_STOCKS_DETAILS`;
export const UPDATE_US_STOCKS_DETAILS = `app/${US_STOCKS_KEY}/UPDATE_US_STOCKS_DETAILS`;
export const GET_US_STOCKS_COLLECTION_LIST = `app/${US_STOCKS_KEY}/GET_US_STOCKS_COLLECTION_LIST`;
export const UPDATE_US_STOCKS_COLLECTION_LIST = `app/${US_STOCKS_KEY}/UPDATE_US_STOCKS_COLLECTION_LIST`;
export const GET_US_STOCKS_COLLECTION_DETAILS = `app/${US_STOCKS_KEY}/GET_US_STOCKS_COLLECTION_DETAILS`;
export const UPDATE_US_STOCKS_COLLECTION_DETAILS = `app/${US_STOCKS_KEY}/UPDATE_US_STOCKS_COLLECTION_DETAILS`;
export const UPDATE_COLLECTION_CACHE = `app/${US_STOCKS_KEY}/UPDATE_COLLECTION_CACHE`;

// US Stocks Collection ids
export enum COLLECTION_IDS {
    WEB_COLLECTION = 'WEB_COLLECTION',
    ALL_STOCKS = 'ALL_STOCKS',
    MOST_POPULAR = 'MOST_POPULAR',
}
