/**
 * @file MinKycClosedAccount constants.
 */

// Navigate types
export const NAVIGATE_PAGE = {
    MOBILE_EMAIL_INPUT_PAGE: 'MOBILE_EMAIL_INPUT_PAGE',
    VERIFY_OTP_PAGE: 'VERIFY_OTP_PAGE',
    PAN_INPUT_PAGE: 'PAN_INPUT_PAGE',
    ACCOUNT_CLOSED_INFO: 'INFO_ACKNOWLEDGEMENT_SCREEN',
    ACCOUNT_DETAILS_INFO: 'PAY_VIA_BANK_TRANSFER',
    DETAILED_ERROR_VIEW_SCREEN: 'DETAILED_ERROR_VIEW_SCREEN',
    ACCOUNT_CLOSURE_TRANSFER_INITIATED: 'ACCOUNT_CLOSURE_TRANSFER_INITIATED',
};

export const BANK_ACCOUNT_FORM_FIELD = {
    BANK_ACCOUNT_FORM_FIELD_UNSPECIFIED: 'BANK_ACCOUNT_FORM_FIELD_UNSPECIFIED',
    BANK_ACCOUNT_FORM_FIELD_IFSC: 'BANK_ACCOUNT_FORM_FIELD_IFSC',
    BANK_ACCOUNT_FORM_FIELD_ACCOUNT_NUMBER: 'BANK_ACCOUNT_FORM_FIELD_ACCOUNT_NUMBER',
    BANK_ACCOUNT_FORM_FIELD_ACC_HOLDER_NAME: 'BANK_ACCOUNT_FORM_FIELD_ACC_HOLDER_NAME',
    BANK_ACCOUNT_FORM_FIELD_BELOW_TITLE: 'BANK_ACCOUNT_FORM_FIELD_BELOW_TITLE',
};

// Component key
export const MIN_KYC_CLOSED_ACCOUNT_KEY = 'MinKycClosedAccount';

// Otp generation action constants
export const GENERATE_OTP_CODE = `app/${MIN_KYC_CLOSED_ACCOUNT_KEY}/GENERATE_OTP_CODE`;
export const GENERATE_OTP_CODE_SUCCESS = `app/${MIN_KYC_CLOSED_ACCOUNT_KEY}/GENERATE_OTP_CODE_SUCCESS`;
export const GENERATE_OTP_CODE_FAILED = `app/${MIN_KYC_CLOSED_ACCOUNT_KEY}/GENERATE_OTP_CODE_FAILED`;

// Verify OTP constants
export const VERIFY_OTP_CODE = `app/${MIN_KYC_CLOSED_ACCOUNT_KEY}/VERIFY_OTP_CODE`;
export const VERIFY_OTP_CODE_SUCCESS = `app/${MIN_KYC_CLOSED_ACCOUNT_KEY}/VERIFY_OTP_CODE_SUCCESS`;
export const VERIFY_OTP_CODE_FAILED = `app/${MIN_KYC_CLOSED_ACCOUNT_KEY}/VERIFY_OTP_CODE_FAILED`;

// Verify PAN constants
export const VERIFY_PAN = `app/${MIN_KYC_CLOSED_ACCOUNT_KEY}/VERIFY_PAN`;
export const VERIFY_PAN_SUCCESS = `app/${MIN_KYC_CLOSED_ACCOUNT_KEY}/VERIFY_PAN_SUCCESS`;
export const VERIFY_PAN_FAILED = `app/${MIN_KYC_CLOSED_ACCOUNT_KEY}/VERIFY_PAN_FAILED`;

// Add alternate account constants
export const ADD_ALTERNATE_ACCOUNT = `app/${MIN_KYC_CLOSED_ACCOUNT_KEY}/ADD_ALTERNATE_ACCOUNT`;
export const ADD_ALTERNATE_ACCOUNT_SUCCESS = `app/${MIN_KYC_CLOSED_ACCOUNT_KEY}/ADD_ALTERNATE_ACCOUNT_SUCCESS`;
export const ADD_ALTERNATE_ACCOUNT_FAILED = `app/${MIN_KYC_CLOSED_ACCOUNT_KEY}/ADD_ALTERNATE_ACCOUNT_FAILED`;

// Navigate to a screen
export const CHANGE_PAGE = `app/${MIN_KYC_CLOSED_ACCOUNT_KEY}/CHANGE_PAGE`;
