/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { IssuedByContent, IssuedByLogo, IssuedByText, IssuedByWrapper, Partnership, TermsAndConditionsUnderIssued } from "./styles";
import { LOGOS_URL_MAP } from "@/constants/AssetConstants";

const IssuedBy: React.FC = () => {
  return (
    <IssuedByWrapper>
      <IssuedByContent>
        <IssuedByText>Issued by</IssuedByText>
        <IssuedByLogo
          src={LOGOS_URL_MAP.FI_FEDERAL}
          alt="Federal Bank logo"
        />
      </IssuedByContent>
      <Partnership>Co-branded partnership with Fi Brand Pvt Ltd</Partnership>
      <TermsAndConditionsUnderIssued>*T&C Apply</TermsAndConditionsUnderIssued>
    </IssuedByWrapper>
  );
};



export default IssuedBy;
