/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";
import TestimonialCard from "./TestimonialCard";
import { MAX_WIDTH_MEDIA_SCREENS, WINDOW_SIZE } from "@/Themes/Device";

const testimonials = [
  {
    testimonial:
      "Lorem ipsum dolor sit amet consectetur. Est amet metus vitae faucibus at. Non semper tortor nisi mauris pellentesque morbi.",
    name: "Saloni.S",
    description: "Credit card user since launch",
  },
  {
    testimonial:
      "Lorem ipsum dolor sit amet consectetur. Est amet metus vitae faucibus at. Non semper tortor nisi mauris pellentesque morbi.",
    name: "Saloni.S",
    description: "Credit card user since launch",
  },
  {
    testimonial:
      "Lorem ipsum dolor sit amet consectetur. Est amet metus vitae faucibus at. Non semper tortor nisi mauris pellentesque morbi.",
    name: "Saloni.S",
    description: "Credit card user since launch",
  },
  {
    testimonial:
      "Lorem ipsum dolor sit amet consectetur. Est amet metus vitae faucibus at. Non semper tortor nisi mauris pellentesque morbi.",
    name: "Saloni.S",
    description: "Credit card user since launch",
  },
];

const TestimonialSection: React.FC = () => {
  return (
    <SectionWrapper>
      <Header>Hear it from our customers</Header>
      <TestimonialContainer>
        <TestimonialWrapper>
          {testimonials.map((testimonial, index) => (
            <TestimonialCard key={index} {...testimonial} />
          ))}
        </TestimonialWrapper>
      </TestimonialContainer>
    </SectionWrapper>
  );
};

const SectionWrapper = styled.section`
  display: flex;
  width: 100%;
  gap: 50px;
  flex-direction: column;

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    gap: 30px;
  }

  @media (max-width: ${WINDOW_SIZE.PHONE}px) {
    gap: 20px;
  }
`;

const TestimonialContainer = styled.div`
  display: flex;
  width: 100%;
  overflow: auto;
  padding-top: 24px;
  scrollbar-width: none;

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    padding-top: 20px;
  }

  @media (max-width: ${WINDOW_SIZE.PHONE}px) {
    padding-top: 10px;
  }
`;

const TestimonialWrapper = styled.div`
  display: flex;
  gap: 24px;
  justify-content: center;
  padding: 0 calc((100% - 1130px) / 2);

  @media (${MAX_WIDTH_MEDIA_SCREENS.tab}) {
    padding: 0 10%;
  }

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    flex-direction: column;
    gap: 40px;
    padding: 0 8%;
  }

  @media (max-width: ${WINDOW_SIZE.PHONE}px) {
    gap: 20px;
    padding: 0 4%;
  }
`;

const Header = styled.header`
  display: flex;
  justify-content: center;
  width: 100%;
  margin: 0 auto;
  color: #333;
  text-align: center;
  font: 500 48px/1 Gilroy, sans-serif;

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    max-width: 100%;
    font-family: Gilroy;
    font-size: 1.8rem;
    font-weight: 600;
    line-height: 2rem;
    text-align: center;
    padding: 0 50px;
  }

  @media (max-width: ${WINDOW_SIZE.PHONE}px) {
    font-size: 30px;
  }
`;

export default TestimonialSection;
