/**
 * This code was generated by Builder.io.
 */
import { MAX_WIDTH_MEDIA_SCREENS, WINDOW_SIZE } from "@/Themes/Device";
import { DEBIT_CARD_IMG_URL_MAP } from "@/constants/AssetConstants";
import React from "react";
import styled from "styled-components";

interface TestimonialCardProps {
  testimonial: string;
  name: string;
  description: string;
}

const TestimonialCard: React.FC<TestimonialCardProps> = ({
  testimonial,
  name,
  description,
}) => {
  return (
    <CardWrapper>
      <InvertedCommaWrapper>
        <InvertedComma
          src={DEBIT_CARD_IMG_URL_MAP.INVERTED_COMMA}
          alt={`Profile picture of ${name}`}
          loading="lazy"
        />
        <InvertedComma
          src={DEBIT_CARD_IMG_URL_MAP.INVERTED_COMMA}
          alt={`Profile picture of ${name}`}
          loading="lazy"
        />
      </InvertedCommaWrapper>
      <TestimonialText>{testimonial}</TestimonialText>
      <Divider />
      <UserInfo>
        <UserName>{name}</UserName>
        <UserDescription>{description}</UserDescription>
      </UserInfo>
    </CardWrapper>
  );
};

const CardWrapper = styled.article`
  border-radius: 52.518px;
  background-color: #fff;
  box-shadow: 0 4px 21px rgba(0, 0, 0, 0.05);
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  padding: 0 33px 62px;
  font-family: Gilroy, sans-serif;
  width: 550px;

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    width: 100%;
    padding: 0 20px 37px;
  }

  @media (max-width: ${WINDOW_SIZE.PHONE}px) {
    padding: 0 10px 20px;
  }
`;

const InvertedCommaWrapper = styled.div`
  display: flex;
  justify-content: space-between;
  margin-top: -24px;
  gap: 5px;
  width: 101px;

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    width: 80px;
    margin-top: -20px;
    margin-left: 10px;
  }

  @media (max-width: ${WINDOW_SIZE.PHONE}px) {
    width: 60px;
    margin-top: -10px;
    margin-left: 20px;
  }
`;

const InvertedComma = styled.img`
  aspect-ratio: 0.7;
  object-fit: contain;
  width: 50%;
`;

const TestimonialText = styled.p`
  margin-top: 30px;
  font-size: 24px;
  color: #313234;
  font-weight: 500;
  letter-spacing: -0.24px;
  line-height: 40px;

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    font-size: 20px;
    margin-top: 20px;
    font-family: Gilroy;
    font-size: 13.29px;
    font-weight: 500;
    line-height: 22.15px;
    letter-spacing: -0.01em;
    text-align: left;
  }

  @media (max-width: ${WINDOW_SIZE.PHONE}px) {
    font-size: 16px;
    line-height: 24px;
    margin-top: 10px;
  }
`;

const UserInfo = styled.div`
  align-self: stretch;
  display: flex;
  flex-direction: column;
  color: #929599;
  padding: 8px;
`;

const UserName = styled.h3`
  font-size: 32px;
  font-weight: 700;
  line-height: 1;
  letter-spacing: -0.32px;

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    font-family: Gilroy;
    font-size: 17.72px;
    font-weight: 700;
    line-height: 21.59px;
    letter-spacing: -0.01em;
    text-align: left;
  }

  @media (max-width: ${WINDOW_SIZE.PHONE}px) {
    font-size: 20px;
  }
`;

const UserDescription = styled.p`
  font-size: 24px;
  font-weight: 500;
  line-height: 2;
  letter-spacing: -0.24px;
  margin-top: 6px;

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    font-family: Gilroy;
    font-size: 13.29px;
    font-weight: 500;
    line-height: 22.15px;
    letter-spacing: -0.01em;
    text-align: left;
  }

  @media (max-width: ${WINDOW_SIZE.PHONE}px) {
    font-size: 16px;
  }
`;

const Divider = styled.div`
  border: 2px solid;
  border-image-source: linear-gradient(
    90deg,
    #f7a800 -2.18%,
    rgba(234, 206, 76, 0) 100%
  );
  width: 100%;
  border-image-slice: 60 30;
  margin: 30px 0;

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    margin: 20px 0;
  }

  @media (max-width: ${WINDOW_SIZE.PHONE}px) {
    margin: 10px 0;
  }
`;

export default TestimonialCard;
