/* eslint-disable max-len */
/**
 * @file contants.js
 *
 * Contains constants for dynamically attaching different paths to express.static in server.js
 */

/**
 * Static files which must be exposed to public must be added here
 * e.g.: a2-form folder has assets like css and js files which are used by HTML in a2-form
 *
 * All files inside the folder will be publicly accessible, hence only those folders which fit the requirement must be added.
 * Do not add a folder in which some files need to be private and some need to be public as all of them would
 * become public due to express.static
 */

const accessibleFolderAssets = [
    { folderName: 'a2-form' }, { folderName: 'styles' },
];

/**
 * Contains redirection URLs for some FAQs and guides pages which throws 404
 * Hence, needs to be redirected to the correct page
 * related sheets link - https://docs.google.com/spreadsheets/d/1ggwc51y5TNtWsSQBZqKW5fvVGQ0aVc8QVrKKFuuhnuI/edit?gid=0#gid=0
 */

const faqUrlRedirectMap = {
    '/credit-card/magnifi/when-will-i-get-my-fi-coins':
      '/credit-card',
    '/amplifi-fi-federal-credit-card/interest,-fees-and-charges/what-are-the-card-replacement-charges':
      '/credit-card',
    '/connected-accounts/about-connected-accounts/why-do-i-need-to-onboard-to-epifi-wealth':
      '/connected-accounts',
    '/about-fi/eligibility-&-access/can-i-open-a-fi-account-without-a-pan-card':
      '',
    '/amplifi-credit-card/interest,-fees-and-charges/what-are-the-card-replacement-charges':
      '/credit-card',
    '/about-fi/general-info/how-do-i-register-a-complaint':
      '/about-fi',
    '/credit-card/simplifi/how-does-an-fd-backed-credit-card-work':
      '/credit-card',
    '/referrals/referee-rewards/i-signed-up-on-fi-using-a-fi.nite-code.-do-i-get-a-reward':
      '/referrals',
    '/amplifi-fi-federal-credit-card/rewards/what-is-the-base-reward-rate-on-my-credit-card':
      '/credit-card',
    '/save/smart-deposit/how-do-i-open-a-fi-smart-deposit':
      '/save',
    '/account-info/account-access/i&apos;m-getting-an-account-validation-error-when-i-try-to-login.-what-do-i-do':
      '/account-info',
    '/rewards/earn-rewards/what/1000':
      '/rewards',
    '/rewards/fi-card-offers/what-offers-are-currently-available-on-the-fi-card/1000':
      '/rewards',
    '/amplifi-credit-card/interest,-fees-and-charges/what-is-the-annual-membership-fee-on-my-credit-card':
      '/credit-card',
    '/credit-card/magnifi-fi-federal-credit-card/do-i-get-access-to-airport-lounges-with-this-card':
      '/credit-card',
    '/debit-card/debit-card-transactions/i/1000':
      '/debit-card',
    '/credit-cards/magnifi-fi-federal-credit-card/do-i-get-access-to-airport-lounges-with-this-card':
      '/credit-card',
    '/onboarding/sign-up-info/can-anyone-open-a-fi-account-without-a-pan-card':
      '/onboarding',
    '/about-fi/privacy-&-safety/is-my-money-safe-with-fi':
      '/about-fi',
    '/debit-card/charges/do-i-get-charged-for-atm-withdrawals/1000':
      '/debit-card',
    '/account-info/account-access/my-mobile-phone&apos;s-lost-or-stolen':
      '/account-info',
    '/referrals/fi.nite-code/my-friend-is-not-able-to-use-my-fi.nite-code.-what-do-i-do':
      '/referrals',
    "/credit-card/simplifi/what's-the-maximum-reward-i-can-earn":
      '/credit-card',
    '/credit-card/simplifi/when-can-i-withdraw-my-fixed-deposit':
      '/credit-card',
    '/amplifi-credit-card/payments/can-i-carry-forward-my-credit-card-balance':
      '/credit-card',
    '/credit-cards/magnifi-fi-federal-credit-card/what-are-the-fees-and-charges-associated-with-this-card':
      '/credit-card',
    '/connected-accounts/about-connected-accounts/how-do-connected-accounts-work':
      '/connected-accounts',
    '/transactions/transaction-issues/what-to-do-if-my-transaction-has-failed-but-money-has-been-debited-from-account':
      '/transactions',
    '/about-fi/general-info/where-can-i-see-fi&apos;s-fees-and-charges':
      '/about-fi',
    '/amplifi-credit-card/card-transactions/how-do-i-set-or-modify-limits-on-my-credit-card':
      '/credit-card',
    '/about-fi/general-info/how-do-i-register-a-complaint/1000':
      '/about-fi',
    '/debit-card/debit-card-transactions/how-do-i-use-card-spending-limits/1000':
      '/debit-card',
    "/save/fixed-deposit/what's-the-minimum-amount-to-open-a-fi-fixed-deposit":
      '/save',
    '/credit-card/magnifi-fi-federal-credit-card/what-are-the-fees-and-charges-associated-with-this-card':
      '/credit-card',
    '/amplifi-fi-federal-credit-card/card-transactions/how-do-i-set-or-modify-limits-on-my-credit-card':
      '/credit-card',
    '/referrals/referral-eligibility/is-there-an-eligibility-criteria-that-i-need-to-meet-before-referring/1000':
      '/referrals',
    '/credit-card/magnifi/what-are-the-fees-and-charges-associated-with-this-card':
      '/credit-card',
    '/debit-card/delivery/when-do-i-get-my-debit-card':
      '/debit-card',
    '/amplifi-fi-federal-credit-card/card-details-and-access/how-do-i-freeze-or-unfreeze-my-credit-card':
      '/credit-card',
    '/account-info/account-details/fi://screen?data=CCk%3D':
      '/account-info',
    '/save/fixed-deposit/i&apos;m-unable-to-create-a-fixed-deposit':
      '/save',
    '/onboarding/troubleshooting/my-video-verification-check-is-failing.-what-do-i-do/1000':
      '/onboarding',
    '/account-info/account-details/where-can-i-see-fi&apos;s-fees-and-charges':
      '/account-info',
    '/credit-card/magnifi-fi-federal-credit-card/what’s-the-maximum-cashback-&-rewards-i-can-earn':
      '/credit-card',
    '/save/fixed-deposit/what-happens-if-i-close-my-fi-fixed-deposit-before-the-maturity-date/1000':
      '/save',
    '/credit-card/simplifi-fi-federal-credit-card/what-are-the-benefits-of-the--simplifi-fi-federal-credit':
      '/credit-card',
    '/credit-card/magnifi-fi-federal-credit-card/can-i-increase-my-credit-limit':
      '/credit-card',
    '/amplifi-credit-card/payments/how-do-i-use-my-credit-card-online':
      '/credit-card',
    '/account-info/account-details/does-fi-offer-loans':
      '/account-info',
    '/onboarding/sign-up-info/can-i-open-a-fi-account-even-if-my-aadhaar-id-does-not-have-a-linked-mobile-number':
      '/onboarding',
    '/save/fixed-deposit/what-is-the-interest-rate-on-fi-fixed-deposits':
      '/save',
    '/amplifi-fi-federal-credit-card/card-transactions/i’m-not-getting-an-otp-for-my-transactions':
      '/credit-card',
    '/save/fixed-deposit/what-is-auto-renew-in-fd/1000':
      '/save',
    '/credit-cards/magnifi-fi-federal-credit-card/i-want-amplifi-fi-federal-credit-card-instead-of-magnifi-fi-federal-credit-card,-what-should-i-do':
      '/credit-card',
    '/amplifi-credit-card/payments/i-did-not-receive-the-correct-bill-amount-matching-my-spending-for-the-last-billing-cycle.-what-should-i-do':
      '/credit-card',
    '/transactions/transaction-issues/what-is-a-digital-receipt-and-how-do-i-find-the-digital-receipt-for-my-transaction':
      '/transactions',
    "/investments/mf-investments/why-am-i-now-seeing-an-'aadhaar-validation-pending'-message-when-i-was-previously-able-to-invest-on-other-platforms":
      '/investments',
    '/jump/about-fi-jump/what-does-xirr-mean':
      '/about-fi',
    '/amplifi-credit-card/general-enquiries/can-i-use-my-credit-card-abroad':
      '/credit-card',
    '/save/smart-deposit/what&apos;s-&apos;smart&apos;-about-a-smart-deposit':
      '/save',
    '/about-fi/general-info/is-fi-a-bank':
      '/about-fi',
    '/amplifi-credit-card':
      '/credit-card',
    '/transaction': '/transactions',
    '/connected-accounts/about-connected-accounts/will-i-get-rewards-for-these-transactions':
      '/connected-accounts',
    '/credit-card/magnifi-fi-federal-credit-card/what-is--magnifi-fi-federal-credit-card-and-what-are-the-benefits':
      '/credit-card',
    '/debit-card/charges/do-i-get-charged-annual-fees-on-the-debit-card':
      '/debit-card',
    '/transactions/fund-transfer/are-ecs-&-nach-facilities-available-for-my-fi-account/1000':
      '/transactions',
    '/video-kyc/video-kyc-call/agent-was-unavailable.-what-should-i-do/1000':
      '/video-kyc',
    '/about-fi/privacy-&-safety/is-my-data-safe':
      '/about-fi',
    '/rewards/earn-rewards/how-do-fi-rewards-work/1000':
      '/rewards',
    '/debit-card/charges/do-i-get-charged-annual-fees-on-the-debit-card/1000':
      '/debit-card',
    '/amplifi-fi-federal-credit-card/card-transactions/i’m-not-able-to-make-any-transactions.-what-do-i-do-now':
      '/credit-card',
    '/amplifi-fi-federal-credit-card/rewards/what-are-the-benefits-of-using-the-credit-card':
      '/credit-card',
    '/about-fi/eligibility-&-access/why-is-fi-only-for-working-professionals':
      '',
    '/amplifi-fi-federal-credit-card/interest,-fees-and-charges/what-is-the-joining-fee-on-my-credit-card':
      '/credit-card',
    '/amplifi-fi-federal-credit-card/statements/how-do-i-download-a-credit-card-statement':
      '/credit-card',
    '/amplifi-credit-card/interest,-fees-and-charges/why-have-i-been-charged-for-‘late-payment’':
      '/credit-card',
    '/credit-cards/magnifi-fi-federal-credit-card/how-do-i-get-weekend-benefits-on-this-card':
      '/credit-card',
    '/account-info/account-summary/how-do-i-get-a-bank-statement/1000':
      '/account-info',
    '/credit-card/simplifi-fi-federal-credit-card/tell-me-about-the-simplifi-fi-federal-credit-card.':
      '/credit-card',
    '/account-info/account-details/what-is-the-minimum-balance-requirement-for-the-saving-account':
      '/account-info',
    '/salary-accounts/registration-issues/i-completed-a-kyc-call-but-was-not-able-to-register-for-salary-account.':
      '',
    '/amplifi-credit-card/general-enquiries/i-see-an-offer-for-a-credit-card-in-the-fi-app.-what-are-the-next-steps-to-get-a-credit-card':
      '/credit-card',
    '/amplifi-credit-card/rewards/will-i-receive-the-base-reward-rate-on-all-transactions':
      '/credit-card',
    '/credit-card/simplifi-fi-federal-credit-card/what’s-the-difference-between-secured-credit-cards-and-unsecured-credit-cards':
      '/credit-card',
    '/us-stocks/selling-us-stocks/how-does-a-sell-order-work-on-us-stocks-on-fi':
      '/us-stocks',
    '/video-kyc/video-kyc-call/my-call-got-disconnected.-what-should-i-do/1000':
      '/video-kyc',
    "/save/smart-deposit/what's-the-minimum-amount-to-open-a-fi-smart-deposit":
      '/save',
    '/rewards/fi-coins/what-are-fi-coins/1000':
      '/rewards',
    '/credit-card/simplifi/can-i-increase-my-credit-limit':
      '/credit-card',
    '/transactions/fund-transfer/are-ecs-&-nach-facilities-available-for-my-savings-account':
      '/transactions',
    "/debit-card/debit-card-transactions/i'm-unable-to-transact-or-withdraw-cash-using-my-fi-card":
      '/debit-card',
    '/amplifi-fi-federal-credit-card/delivery/when-do-i-get-my-credit-card':
      '/credit-card',
    '/onboarding/troubleshooting/i&apos;m-stuck-after-entering-my-date-of-birth.-what-do-i-do':
      '/onboarding',
    '/amplifi-credit-card/rewards/do-i-get-access-to-airport-lounges-through-this-card':
      '/credit-card',
    '/credit-card/simplifi/what-are-the-benefits-of-the--simplifi-fi-federal-credit':
      '/credit-card',
    '/connected-accounts/about-connected-accounts/is-the-connected-accounts-feature-available-on-ios':
      '/connected-accounts',
    '/credit-card/magnifi-fi-federal-credit-card/where-do-i-receive-the-cashback-and-other-rewards':
      '/credit-card',
    '/video-kyc/video-kyc-call/agent-was-unavailable.-what-should-i-do':
      '/video-kyc',
    "/credit-card/simplifi-fi-federal-credit-card/what's-the-minimum-fixed-deposit-amount-required-for-the-credit-card":
      '/credit-card',
    '/onboarding/troubleshooting/i-didn/1000':
      '/onboarding',
    '/save/fixed-deposit/what-is-the-interest-rate-on-fi-fixed-deposits/1000':
      '/save',
    '/amplifi-credit-card/card-transactions/i’m-not-getting-an-otp-for-my-transactions':
      '/credit-card',
    '/credit-card/simplifi/why-do-i-have-to-open-an-fd-to-get-this-credit-card':
      '/credit-card',
    '/rewards/fi-coins/where-can-fi-coins-be-spent/1000':
      '/rewards',
    '/referrals/referral-eligibility/what-is-the-referral-program/1000':
      '/referrals',
    '/credit-card/magnifi-fi-federal-credit-card/when-will-i-get-my-fi-coins':
      '/credit-card',
    '/salary-accounts/general-enquiries/how-do-i-get-a-salary-account':
      '',
    '/rewards/fi-card-offers/what-offers-are-currently-available-on-the-fi-card':
      '/rewards',
    '/amplifi-credit-card/rewards/what-is-the-base-reward-rate-on-my-credit-card':
      '/credit-card',
    '/amplifi-fi-federal-credit-card/interest,-fees-and-charges/why-are-you-charging-me-an-additional-fee-for-international-transactions':
      '/credit-card',
    '/loan-against-mutual-fund/payments-and-emi/what-amount-will-be-deducted-every-month-from-my-savings-a/c-if-i-setup-the-recommended-emi-auto-pay':
      '/loan-against-mf',
    '/amplifi-credit-card/rewards/what-are-the-benefits-of-using-the-credit-card':
      '/credit-card',
    '/transaction/load-money/how-do-i-add-money-to-my-fi-account':
      '/transactions',
    '/loan-against-mutual-fund/loan-details/once-pledged,-what-happens-to-my-mutual-funds':
      '/loan-against-mf',
    '/account-info/account-access/do-i-need-a-login-pin-to-access-the-fi-app/1000':
      '/account-info',
    '/credit-card/simplifi/tell-me-about-the-simplifi-fi-federal-credit-card.':
      '/credit-card',
    '/credit-card/simplifi/what-are-the-fees-and-charges-for-using-the-credit-card':
      '/credit-card',
    '/credit-card/magnifi/can-i-increase-my-credit-limit':
      '/credit-card',
    '/amplifi-fi-federal-credit-card/delivery/what-should-i-do-if-i-haven’t-received-my-credit-card':
      '/credit-card',
    '/credit-card/simplifi/what-are-the-benefits-of-the-simplifi-credit-card':
      '/credit-card',
    '/debit-card/delivery/what-happens-if-i-miss-my-debit-card-delivery/1000':
      '/debit-card',
    '/amplifi-fi-federal-credit-card':
      '/credit-card',
    '/debit-card/debit-card-transactions/where-can-i-view-my-debit-card-spends':
      '/debit-card',
    '/save/smart-deposit/can-i-withdraw-money-from-my-fi-smart-deposit-anytime':
      '/save',
    '/amplifi-credit-card/interest,-fees-and-charges/what-is-the-joining-fee-on-my-credit-card':
      '/credit-card',
    '/transactions/load-money/i-tried-to-add-money-to-my-fi-account.-money-was-debited-from-my-source-account-but-not-credited-to-the-fi-account.':
      '/transactions',
    '/amplifi-fi-federal-credit-card/payments/how-do-i-make-repayments-with-my-credit-card':
      '/credit-card',
    '/referrals/referrer-rewards/about':
      '/referrals',
    '/credit-cards/magnifi-fi-federal-credit-card/will-i-need-to-submit-any-documentation-to-get-this-card':
      '/credit-card',
    '/investments/mf-investments/how-do-i-generate-a-consolidated-account-statement/1000':
      '/investments',
    "/account-info/account-access/i'm-getting-an-account-validation-error-when-i-try-to-login.-what-do-i-do":
      '/account-info',
    '/credit-cards/magnifi-fi-federal-credit-card/can-i-increase-my-credit-limit':
      '/credit-card',
    '/amplifi-fi-federal-credit-card/general-enquiries/i-see-an-offer-for-a-credit-card-in-the-fi-app.-what-are-the-next-steps-to-get-a-credit-card':
      '/credit-card',
    '/salary-accounts/general-enquiries/what-benefits-does-the-salary-account-provide':
      '',
    '/us-stocks/getting-started-with-us-stocks/why-am-i-stuck-in-the-us-stocks-account-creation-process':
      '/us-stocks',
    '/credit-cards/magnifi-fi-federal-credit-card/when-will-i-get-my-fi-coins':
      '/credit-card',
    '/salary-accounts/unlocking-benefits/received-salary-in-my-savings-account,-but-salary-benefits-did-not-get-activated':
      '',
    '/video-kyc/video-kyc-call/how-do-i-make-a-video-kyc-call/1000':
      '/video-kyc',
    '/amplifi-credit-card/privacy-and-security/is-the-credit-card-safe-to-use':
      '/credit-card',
    '/amplifi-credit-card/card-transactions/where-can-i-view-my-credit-card-spends':
      '/credit-card',
    '/onboarding/sign-up-info/i-have-an-existing-account-with-federal-bank.-can-i-create-an-account-with-fi':
      '/onboarding',
    '/referrals/fi.nite-code/my-code-did-not-work:-friend-entered-finite-code-but-is-unable-to-get-access-to-the-app':
      '/referrals',
    '/amplifi-fi-federal-credit-card/rewards/what-happens-to-my-fi-coins-if-i-cancel-the-transaction-that-got-me-the-fi-coins':
      '/credit-card',
    '/amplifi-fi-federal-credit-card/card-details-and-access/how-do-i-reset-my-credit-card-pin':
      '/credit-card',
    '/credit-card/magnifi/what-are-the-interest-and-fees-on-late-payment-of-bill':
      '/credit-card',
    '/onboarding/troubleshooting/the-otp-verification-of-my-aadhar-failed':
      '/onboarding',
    '/video-kyc/video-kyc-call/1000':
      '/video-kyc',
    '/jump/about-fi-jump/what-happens-when-an-investment-matures':
      '/about-fi',
    '/us-stocks/getting-started-with-us-stocks/i-am-being-asked-to-‘establish-my-source-of-funds’.-why-am-i-seeing-this':
      '/us-stocks',
    '/credit-card/magnifi-fi-federal-credit-card/how-do-i-repay-my-credit-card-bill':
      '/credit-card',
    '/save/fixed-deposit/what-happens-if-i-close-my-fi-fixed-deposit-before-the-maturity-date':
      '/save',
    '/re-onboarding/info-&-troubleshooting/how-do-i-update-my-phone-number/1000':
      '/onboarding',
    '/profile/account-info/how-do-i-find-my-account-number-or-ifsc-code-or-upi-id/1000':
      '/account-info',
    '/jump/about-fi-jump/what-are-the-investment-limits-under-jump':
      '/about-fi',
    '/account-info/account-access/i&apos;m-unable-to-login-to-my-app':
      '/account-info',
    '/amplifi-credit-card/card-details-and-access/how-do-i-freeze-or-unfreeze-my-credit-card':
      '/credit-card',
    '/credit-card/magnifi-fi-federal-credit-card/what-are-the-interest-and-fees-on-late-payment-of-bill':
      '/credit-card',
    '/credit-card/magnifi/will-i-need-to-submit-any-documentation-to-get-this-card':
      '/credit-card',
    '/debit-card/card-loss-or-damage/my-debit-card&apos;s-misplaced':
      '/debit-card',
    '/re-onboarding/info-&-troubleshooting/what-happens-if-i-uninstall-my-fi-app':
      '/onboarding',
    '/credit-card/magnifi/what-is--magnifi-credit-card-and-what-are-the-benefits':
      '/credit-card',
    '/amplifi-credit-card/rewards/i-have-not-received-my-fi-coins.-what-do-i-do':
      '/credit-card',
    '/amplifi-fi-federal-credit-card/rewards/will-i-receive-the-base-reward-rate-on-all-transactions':
      '/credit-card',
    '/about': '/',
    "/save/fixed-deposit/what's-the-minimum-time-duration-for-a-fi-fixed-deposit":
      '/save',
    '/amplifi-fi-federal-credit-card/interest,-fees-and-charges/what-is-the-forex-markup-on-international-transactions-with-my-credit-card':
      '/credit-card',
    '/credit-card/general-enquiries/i-was-eligible-for-a-credit-card,-but-i-couldn’t-get-it.-what-do-i-do-next':
      '/credit-card',
    '/account-info/account-details/fi:/screen?data=CCk%3D':
      '/account-info',
    '/rewards/earn-rewards/i-just-grew-a-money-plant-and-chose-a-reward.-i-don&apos;t-see-it-in-my-account-yet':
      '/rewards',
    '/amplifi-fi-federal-credit-card/interest,-fees-and-charges/what-is-the-annual-membership-fee-on-my-credit-card':
      '/credit-card',
    '/debit-card/card-loss-or-damage/my-debit-card&apos;s-damaged':
      '/debit-card',
    '/amplifi-fi-federal-credit-card/card-details-and-access/why-was-i-not-able-to-withdraw-cash-from-an-atm-using-my-credit-card':
      '/credit-card',
    "/save/smart-deposit/what's-the-minimum-time-period-for-fi-smart-deposits":
      '/save',
    '/amplifi-credit-card/card-details-and-access/how-do-i-see-my-card-details':
      '/credit-card',
    '/credit-card/simplifi/how-do-i-repay-my-credit-card-bill':
      '/credit-card',
    '/debit-card/card-loss-or-damage/my-debit-card&apos;s-lost-or-stolen':
      '/debit-card',
    '/debit-card/debit-card-transactions/i&apos;m-unable-to-receive-a-transaction-otp':
      '/debit-card',
    '/amplifi-fi-federal-credit-card/rewards/how-does-the-5x-reward-work':
      '/credit-card',
    '/re-onboarding/info-&-troubleshooting/i&apos;m-unable-to-move-past-the-video-verification-stage.-what-do-i-do':
      '/onboarding',
    '/about-fi/general-info/what-is-the-minimum-balance-requirement-for-the-saving-account':
      '/about-fi',
    '/amplifi-credit-card/card-details-and-access/how-do-i-reset-my-credit-card-pin':
      '/credit-card',
    '/save/fixed-deposit/how-do-i-open-a-fi-fixed-deposit':
      '/save',
    "/referrals/referral-eligibility/i'm-not-able-to-refer-anyone-even-though-i've-completed-10-days-on-fi-and-maintained-an-average-balance-of-₹2000.":
      '/referrals',
    '/account-info/account-details/does-fi-offer-credit-cards':
      '/credit-card',
    '/account-info/account-details/how-do-i-deposit-cash-into-my-savings-account':
      '/account-info',
    '/onboarding/troubleshooting/why-am-i-not-able-to-sign-up-with-my-ckyc':
      '/onboarding',
    '/amplifi-credit-card/delivery/what-should-i-do-if-i-haven’t-received-my-credit-card':
      '/credit-card',
    '/credit-card/magnifi/where-do-i-receive-the-cashback-and-other-rewards':
      '/credit-card',
    '/jump/about-fi-jump/how-does-jump-work':
      '/about-fi',
    '/onboarding/verifying-your-work-status/why-should-i-link-my-primary-gmail-with-fi':
      '/onboarding',
    '/amplifi-credit-card/card-details-and-access/why-am-i-asked-to-do-a-‘facematch’-check-every-time-i-modify-my-card-settings':
      '/credit-card',
    '/amplifi-credit-card/payments/how-do-i-make-repayments-with-my-credit-card':
      '/credit-card',
    '/amplifi-fi-federal-credit-card/card-details-and-access/how-do-i-see-my-card-details':
      '/credit-card',
    '/amplifi-credit-card/card-details-and-access/how-do-i-check-my-credit-limit':
      '/credit-card',
    '/amplifi-fi-federal-credit-card/rewards/i-have-not-received-my-fi-coins.-what-do-i-do':
      '/credit-card',
    '/onboarding/sign-up-info/which-email-id-can-i-use-to-sign-up-on-fi':
      '/onboarding',
    '/credit-card/magnifi-fi-federal-credit-card/can-i-use-the-magnifi-fi-federal-credit-card-abroad':
      '/credit-card',
    '/amplifi-fi-federal-credit-card/rewards/do-i-get-access-to-airport-lounges-through-this-card':
      '/credit-card',
    '/jump/investments-and-payments/i-am-seeing-a-maturity-payout-activity-with-status-failed-and-have-not-received-the-amount':
      '/investments',
    '/video-kyc/about-video-kyc/do-i-need-to-complete-a-video-kyc-call/1000':
      '/video-kyc',
    "/credit-card/simplifi/what's-the-minimum-fixed-deposit-amount-required-for-the-credit-card":
      '/credit-card',
    '/amplifi-credit-card/rewards/what-happens-to-my-fi-coins-if-i-cancel-the-transaction-that-got-me-the-fi-coins':
      '/credit-card',
    '/credit-card/magnifi-fi-federal-credit-card/how-do-i-get-weekend-benefits-on-this-card':
      '/credit-card',
    '/credit-card/simplifi-fi-federal-credit-card/how-do-i-build-my-credit-score-using-the--simplifi-fi-federal-credit-card':
      '/credit-card',
    '/amplifi-fi-federal-credit-card/statements/when-will-i-receive-my-credit-card-statement':
      '/credit-card',
    '/jump/about-fi-jump/what-are-the-fees-charged-by-fi-for-investing-in-jump':
      '/about-fi',
    '/connected-accounts/connecting-your-bank-account/how-do-i-connect-my-account/1000':
      '/connected-accounts',
    '/referrals/referee-rewards/i-joined-using-a-finite-code-but-i-did-not-get-a-reward':
      '/referrals',
    '/amplifi-credit-card/rewards/how-does-the-5x-reward-work':
      '/credit-card',
    '/amplifi-credit-card/interest,-fees-and-charges/what-are-the-over-limit-charges-on-my-credit-card':
      '/credit-card',
    '/amplifi-fi-federal-credit-card/card-transactions/where-can-i-view-my-credit-card-spends':
      '/credit-card',
    '/amplifi-credit-card/interest,-fees-and-charges/why-are-you-charging-me-an-additional-fee-for-international-transactions':
      '/credit-card',
    "/transactions/transaction-issues/i-made-a-transaction-and-my-balance-isn't-updated":
      '/transactions',
    '/onboarding/verifying-your-work-status/why-does-fi-need-my-credit-report':
      '/onboarding',
    '/credit-cards/magnifi-fi-federal-credit-card/what-is--magnifi-fi-federal-credit-card-and-what-are-the-benefits':
      '/credit-card',
    '/onboarding/verifying-your-work-status/why-was-my-application-rejected':
      '/onboarding',
    '/amplifi-credit-card/statements/how-do-i-download-a-credit-card-statement':
      '/credit-card',
    '/transactions/load-money/how-do-i-add-money-to-my-fi-account':
      '/transactions',
    '/credit-cards/magnifi-fi-federal-credit-card/can-i-use-the-magnifi-fi-federal-credit-card-abroad':
      '/credit-card',
    '/video-kyc/video-kyc-call/what-documents-do-i-need-to-complete-a-video-kyc-call/1000':
      '/video-kyc',
    '/amplifi-credit-card/card-details-and-access/why-was-i-not-able-to-withdraw-cash-from-an-atm-using-my-credit-card':
      '/credit-card',
    '/amplifi-fi-federal-credit-card/payments/how-do-i-get-a-refund-for-the-excess-balance-on-my-credit-card':
      '/credit-card',
    '/amplifi-credit-card/card-details-and-access/how-do-i-activate-my-digital-credit-card':
      '/credit-card',
    '/credit-card/magnifi-fi-federal-credit-card/will-i-need-to-submit-any-documentation-to-get-this-card':
      '/credit-card',
    '/profile/legal/what-is-fi&apos;s-privacy-policy':
      '',
    '/about-fi/general-info/what’s-the-interest-rate-on-my-savings-account':
      '/about-fi',
    '/amplifi-fi-federal-credit-card/general-enquiries/what-are-the-fees-and-charges-for-using-the-credit-card':
      '/credit-card',
    '/save/smart-deposit/what/1000':
      '/save',
    '/amplifi-fi-federal-credit-card/card-details-and-access/how-do-i-check-my-credit-limit':
      '/credit-card',
    '/amplifi-fi-federal-credit-card/card-details-and-access/what-do-i-do-if-my-credit-card-has-been-lost-or-damaged':
      '/credit-card',
    '/credit-card/simplifi-fi-federal-credit-card/how-does-an-fd-backed-credit-card-work':
      '/credit-card',
    '/credit-card/magnifi/do-i-get-access-to-airport-lounges-with-this-card':
      '/credit-card',
    "/save/smart-deposit/what's-the-interest-rate-on-fi-smart-deposits":
      '/save',
    '/amplifi-credit-card/delivery/when-do-i-get-my-credit-card':
      '/credit-card',
    '/credit-card/simplifi/how-do-i-build-my-credit-score-using-the--simplifi-fi-federal-credit-card':
      '/credit-card',
    '/account-info/account-details/how-do-i-order-a-cheque-book/1000':
      '/account-info',
    '/loan-against-mutual-fund':
      '/loan-against-mf',
    '/about-fi/general-info/does-fi-offer-credit-cards':
      '/credit-card',
    '/account-info/account-details/can-i-get-a-passbook/1000':
      '/account-info',
    '/fit/managing-fit-rules/my-account-did-not-have-enough-balance-so-the-rule-didn&apos;t-work.':
      '/fit',
    '/salary-accounts/general-enquiries/what-is-a-salary-account':
      '',
    '/amplifi-fi-federal-credit-card/general-enquiries/can-i-use-my-credit-card-abroad':
      '/credit-card',
    '/credit-card/magnifi/what’s-the-maximum-cashback-&-rewards-i-can-earn':
      '/credit-card',
    '/jump/about-fi-jump/why-is-my-withdrawable-amount-lower-than-the-current-value-of-my-investment':
      '/about-fi',
    '/amplifi-fi-federal-credit-card/interest,-fees-and-charges/why-have-i-been-charged-for-‘late-payment’':
      '/credit-card',
    '/save/smart-deposit/i&apos;m-unable-to-open-a-smart-deposit':
      '/save',
    '/amplifi-fi-federal-credit-card/privacy-and-security/is-the-credit-card-safe-to-use':
      '/credit-card',
    '': '/',
    '/about-fi/general-info/does-fi-offer-loans':
      '/about-fi',
    '/onboarding/troubleshooting/i-didn&apos;t-receive-my-aadhar-otp':
      '/onboarding',
    '/investments/investments-onboarding/i&apos;ve-already-signed-up-on-fi.-why-should-i-provide-additional-details-to-use-investments':
      '/onboarding',
    '/credit-card/magnifi/how-do-i-get-weekend-benefits-on-this-card':
      '/credit-card',
    '/account-info/account-details/fi://screen?data=CJ8GyhRfCll0eXBlLmdvb2dsZWFwaXMuY29tL3R5cGVzLmRlZXBsaW5rX3NjcmVlbl9vcHRpb24uc2FfY2xvc3VyZS5TYUNsb3N1cmVCZW5lZml0U2NyZWVuT3B0aW9ucxICEAI%3D':
      '/account-info',
    '/amplifi-fi-federal-credit-card/card-details-and-access/how-do-i-activate-my-digital-credit-card':
      '/credit-card',
    '/transactions/fund-transfer/are-ecs-&-nach-facilities-available-for-my-fi-account':
      '/transactions',
    '/amplifi-credit-card/statements/when-will-i-receive-my-credit-card-statement':
      '/credit-card',
    '/transactions/fund-transfer/can-i-send-money-to-someone-outside-india':
      '/transactions',
    '/credit-card/magnifi/how-do-i-repay-my-credit-card-bill':
      '/credit-card',
    '/amplifi-credit-card/interest,-fees-and-charges/what-is-the-forex-markup-on-international-transactions-with-my-credit-card':
      '/credit-card',
    '/video-kyc/about-video-kyc/why-do-i-need-to-complete-re-kyc/periodic-kyc':
      '/video-kyc',
    '/save/fixed-deposit/what-is-interest-payout-option-in-fd/1000':
      '/save',
    '/investments/mf-investments/how-do-i-change-the-auto-invest-date/amount':
      '/investments',
    '/1000': '/',
    '/credit-card/simplifi-fi-federal-credit-card/why-do-i-have-to-open-an-fd-to-get-this-credit-card':
      '/credit-card',
    '/debit-cardYour': '/debit-card',
    "/transactions/transaction-issues/what-does-'raise-dispute'-mean":
      '/transactions',
    '/amplifi-fi-federal-credit-card/payments/how-do-i-use-my-credit-card-online':
      '/credit-card',
    '/onboarding/verifying-your-work-status/my-company-is-not-listed.-what-should-i-do':
      '/onboarding',
    '/video-kyc/about-video-kyc/how-can-i-complete-re-kyc':
      '/video-kyc',
    '/credit-cards/magnifi-fi-federal-credit-card/where-do-i-receive-the-cashback-and-other-rewards':
      '/credit-card',
    '/credit-card/simplifi/will-i-get-a-100%-credit-limit-on-my-fixed-deposit':
      '/credit-card',
    '/amplifi-credit-card/card-details-and-access/how-do-i-activate-my-physical-credit-card':
      '/credit-card',
    '/amplifi-credit-card/card-details-and-access/what-do-i-do-if-my-credit-card-has-been-lost-or-damaged':
      '/credit-card',
    '/credit-card/magnifi/can-i-use-the-magnifi-fi-federal-credit-card-abroad':
      '/credit-card',
    '/amplifi-fi-federal-credit-card/interest,-fees-and-charges/what-are-the-over-limit-charges-on-my-credit-card':
      '/credit-card',
    '/debit-card/delivery/when-do-i-get-my-debit-card/1000':
      '/debit-card',
    '/about-fi/eligibility-&-access/i-have-an-existing-account-with-federal-bank.-can-i-create-an-account-with-fi':
      '',
    '/amplifi-fi-federal-credit-card/payments/i-did-not-receive-the-correct-bill-amount-matching-my-spending-for-the-last-billing-cycle.-what-should-i-do':
      '/credit-card',
    '/video-kyc/about-video-kyc/who-needs-to-complete-re-kyc/periodic-kyc':
      '/video-kyc',
    '/about-fi/general-info/can-i-directly-call-federal-bank-about-issues-with-my-fi-account':
      '/about-fi',
    '/credit-cards/magnifi-fi-federal-credit-card/how-do-i-repay-my-credit-card-bill':
      '/credit-card',
    '/onboarding/verifying-your-work-status/why-do-you-need-my-work-email':
      '/onboarding',
    '/credit-card/simplifi/what’s-the-difference-between-secured-credit-cards-and-unsecured-credit-cards':
      '/credit-card',
    '/onboarding/troubleshooting/my-phone-isn&apos;t-getting-registered.-what-do-i-do':
      '/onboarding',
    '/amplifi-credit-card/card-transactions/i’m-not-able-to-make-any-transactions.-what-do-i-do-now':
      '/credit-card',
    '/credit-card/magnifi-fi-federal-credit-card/i-want-amplifi-fi-federal-credit-card-instead-of-magnifi-fi-federal-credit-card,-what-should-i-do':
      '/credit-card',
    '/amplifi-credit-card/general-enquiries/what-are-the-fees-and-charges-for-using-the-credit-card':
      '/credit-card',
    '/credit-card/card-details-and-access/how-do-i-get-a-noc-for-my-credit-card':
      '/credit-card',
    '/jump/about-fi-jump/what-is-jump':
      '/about-fi',
    '/account-info/account-access/i/1000':
      '/account-info',
    '/debit-card/charges/what-are-the-replacement-charges-for-a-debit-card':
      '/debit-card',
    '/credit-card/simplifi-fi-federal-credit-card/will-i-get-a-100%-credit-limit-on-my-fixed-deposit':
      '/credit-card',
    '/save/fixed-deposit/tell-me-more-about-fixed-deposits/1000':
      '/about-fi',
    '/amplifi-fi-federal-credit-card/card-details-and-access/how-do-i-activate-my-physical-credit-card':
      '/credit-card',
    '/amplifi-credit-card/payments/how-do-i-get-a-refund-for-the-excess-balance-on-my-credit-card':
      '/credit-card',
    '/credit-cards/magnifi-fi-federal-credit-card/what-are-the-interest-and-fees-on-late-payment-of-bill':
      '/credit-card',
    '/credit-cards/magnifi-fi-federal-credit-card/what’s-the-maximum-cashback-&-rewards-i-can-earn':
      '/credit-card',
};

const guidesUrlRedirectMap = {
    '/what-are-the-top-us-stocks-in-the-market': '/us-stocks/what-are-the-top-us-stocks-in-the-market',
    '/things-to-bear-in-mind-while-investing-in-the-us-stock-market-online': '/us-stocks/things-to-bear-in-mind-while-investing-in-the-us-stock-market-online',
    '/india-tax-filing-us-stocks-fi-money': '/us-stocks/india-tax-filing-us-stocks-fi-money',
    '/fractional-us-shares-everything-you-need-to-know': '/us-stocks/fractional-us-shares-everything-you-need-to-know',
    '/how-to-invest-in-the-s-p-500-today': '/us-stocks/how-to-invest-in-the-s-p-500-today',
    '/how-to-predict-the-us-stock-market': '/us-stocks/how-to-predict-the-us-stock-market',
    '/what-are-the-indices-used-in-the-us-market-differences-and-comparisons': '/us-stocks/what-are-the-indices-used-in-the-us-market-differences-and-comparisons',
};

module.exports = {
    accessibleFolderAssets,
    faqUrlRedirectMap,
    guidesUrlRedirectMap,
};
