import { DEBIT_CARD_IMG_URL_MAP } from "@/constants/AssetConstants";

/**
 * This code was generated by Builder.io.
 */
export const featureData = [
  {
    title: "Earn more with 2% cashback*! 💳",
    description:
      "Enjoy cashback on any spends — be it shopping, dining out, or booking holiday flights.",
    note: "*Applicable on select plans. 2% cashback is capped at ₹500 a month.",
    imageSrc: DEBIT_CARD_IMG_URL_MAP.TWO_PERCENT,
  },
  {
    title: "Unlock 4X Rewards*! 🎁",
    description:
      "Pay with your Fi-Federal Debit Card and earn 4X rewards*. Redeem for amazing vouchers and discounts!",
    note: "*T&C Apply",
    imageSrc: DEBIT_CARD_IMG_URL_MAP.FOUR_X,
  },
  {
    title: "Free* ATM Withdrawals 🏧",
    description:
      "Access your money conveniently without worrying about extra charges. Enjoy free* ATM withdrawals nationwide.",
    note: "*T&C Apply",
    imageSrc: DEBIT_CARD_IMG_URL_MAP.ATM_IMAGE,
  },
];
