/**
 * This code was generated by Builder.io.
 */
import { WINDOW_SIZE, MAX_WIDTH_MEDIA_SCREENS } from "@/Themes/Device";
import React from "react";
import styled from "styled-components";

interface FeatureCardProps {
  title: string;
  description: string;
  note?: string;
  imageSrc: string;
}

const FeatureCard: React.FC<FeatureCardProps> = ({
  title,
  description,
  note,
  imageSrc,
}) => {
  return (
    <Card>
      <Content>
        <Title>{title}</Title>
        <Description>{description}</Description>
        {note && <Note>{note}</Note>}
      </Content>
      <ImageWrapper>
        <Image src={imageSrc} alt="" />
      </ImageWrapper>
    </Card>
  );
};

const Card = styled.article`
  display: flex;
  width: 100%;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  border-radius: 24px;
  background-color: #fff;
  margin-top: 24px;
  padding: 20px 16px;
  font-family: Inter, sans-serif;
  text-align: center;
`;

const Content = styled.div`
  display: flex;
  width: 100%;
  flex-direction: column;
  align-items: center;
  justify-content: center;
`;

const Title = styled.h2`
  color: #333;
  font-feature-settings: "liga" off, "clig" off;
  font: 600 32px/1 Gilroy, sans-serif;

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    font-family: Gilroy;
    font-size: 1.5rem;
    font-weight: 600;
    line-height: 1.8rem;
    text-align: center;
  }

  @media (max-width: ${WINDOW_SIZE.PHONE}px) {
    font-size: 24px;
  }
`;

const Description = styled.p`
  color: #646464;
  font-size: 20px;
  line-height: 25px;
  margin-top: 8px;

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    font-family: Inter;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5rem;
    text-align: center;
    padding: 0px 30px;
  }

  @media (max-width: ${WINDOW_SIZE.PHONE}px) {
    font-size: 18px;
  }
`;

const Note = styled.p`
  color: #a4a4a4;
  font-feature-settings: "liga" off, "clig" off;
  font-size: 12px;
  line-height: 12px;
  margin-top: 8px;

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    font-family: Inter;
    font-size: 0.6rem;
    font-weight: 500;
    line-height: 0.8rem;
    text-align: center;
    padding: 0 50px;
  }

  @media (max-width: ${WINDOW_SIZE.PHONE}px) {
    font-size: 10px;
  }
`;

const ImageWrapper = styled.div`
  width: 100%;
  margin-top: 24px;
`;

const Image = styled.img`
  aspect-ratio: 1.14;
  object-fit: contain;
  object-position: center;
  width: 100%;
`;

export default FeatureCard;
