/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";
import FeatureCard from "./FeatureCard";
import { featureData } from "./featureData";
import { MAX_WIDTH_MEDIA_SCREENS, WINDOW_SIZE } from "@/Themes/Device";

const CardFeatures: React.FC = () => {
  return (
    <Container>
      <Title>Best card for your spends in India too</Title>
      {featureData.map((feature, index) => (
        <FeatureCard key={index} {...feature} />
      ))}
    </Container>
  );
};

const Container = styled.section`
  display: none;
  width: 100%;
  max-width: 1130px;
  flex-direction: column;
  justify-content: center;

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    display: flex;
    padding: 0 20px;
  }
`;

const Title = styled.h1`
  color: #333;
  text-align: center;
  font-feature-settings: "liga" off, "clig" off;
  font: 600 48px/1 Gilroy, sans-serif;

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    font-family: Gilroy;
    font-size: 1.6rem;
    font-weight: 600;
    line-height: 2rem;
    text-align: center;
    padding: 0 50px;
  }

  @media (max-width: ${WINDOW_SIZE.PHONE}px) {
    font-size: 30px;
  }
`;

export default CardFeatures;
