/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { ImageWrapper, StyledImage, TermsAndConditionsUnderImage } from "./styles";
import { DEBIT_CARD_IMG_URL_MAP } from "@/constants/AssetConstants";

const CardImage: React.FC = () => {
  return (
    <ImageWrapper>
      <StyledImage
        src={DEBIT_CARD_IMG_URL_MAP.PASSPORT_DEBIT_CARD}
        alt="Fi-Federal Debit Card"
      />
      <TermsAndConditionsUnderImage>*T&C Apply</TermsAndConditionsUnderImage>

    </ImageWrapper>
  );
};

export default CardImage;
