/**
 * This code was generated by Builder.io.
 */
import { DEBIT_CARD_IMG_URL_MAP } from "@/constants/AssetConstants";
import TravelTip from "./TravelTip";

export const offerData = [
  {
    title: "Trip on these offers 🎁",
    description:
      "Offers on top global brands like Grab, Careem, Hotels.com, etc.",
    imageSrc: DEBIT_CARD_IMG_URL_MAP.CARD_OFFERS,
  },
  {
    title: "You remain 100% in control ⚙️",
    description:
      "Edit transaction limits, enable global payments, or freeze it all with 1-tap.",
    imageSrc: DEBIT_CARD_IMG_URL_MAP.CARD_CUSTOMIZATION,
    extra: TravelTip,
  },
  {
    title: "0 TCS ⏩",
    description:
      `No TCS is deducted on international spends till ₹7 Lakh
      T&C Apply`,
    imageSrc: DEBIT_CARD_IMG_URL_MAP.ZERO_IMAGE,
  },
];
