/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";
import OfferCard from "./OfferCard";
import { offerData } from "./data";
import { MAX_WIDTH_MEDIA_SCREENS } from "@/Themes/Device";

interface TravelOffersProps { }

const TravelOffers: React.FC<TravelOffersProps> = () => {
  return (
    <>
      <OfferContainer>
        {offerData.map((offer, index) => (
          <OfferCard key={index} {...offer} index={index} />
        ))}
      </OfferContainer>
    </>
  );
};

const OfferContainer = styled.section`
  padding: 64px 0;
  display: flex;
  flex-direction: column;
  align-items: center;
  display: flex;
  width: 100%;
  max-width: 1130px;
  gap: 100px;

  @media (${MAX_WIDTH_MEDIA_SCREENS.tab}) {
    max-width: 80%;
  }

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    gap: 40px;
    max-width: 100%;
    padding: 16px 0;
  }
`;

export default TravelOffers;
