/**
 * This code was generated by Builder.io.
 */
import { MAX_WIDTH_MEDIA_SCREENS, WINDOW_SIZE } from "@/Themes/Device";
import React from "react";
import styled from "styled-components";

interface OfferCardProps {
  title: string;
  description: string;
  imageSrc: string;
  index: number;
  extra?: React.FC;
}

const OfferCard: React.FC<OfferCardProps> = ({
  title,
  description,
  imageSrc,
  index,
  extra: ExtraData,
}) => {
  return (
    <CardWrapper index={index}>
      {
        index % 2 === 0 ? (
          <>
            <TextContent index={index}>
              <CardTitle>{title}</CardTitle>
              <CardDescription>{description}</CardDescription>
            </TextContent>
            <ImageWrapper index={index} hasExtraData={!!ExtraData}>
              <CardImage src={imageSrc} alt={title} />
            </ImageWrapper>
          </>
        ) : (
          <>
            <ImageWrapper index={index} hasExtraData={!!ExtraData}>
              <CardImage src={imageSrc} alt={title} />
            </ImageWrapper>
            <TextContent index={index}>
              <CardTitle>{title}</CardTitle>
              <CardDescription>{description}</CardDescription>
            </TextContent>
          </>
        )
      }
      {ExtraData && <ExtraData />}
    </CardWrapper>
  );
};

const CardWrapper = styled.article<{ index: number }>`
  display: grid;
  width: 100%;
  align-items: center;
  justify-content: center;
  grid-template-columns: 50% 50%;

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    grid-template-columns: 100%;
    gap: 30px;
    max-width: 100%;
    padding: 0 20px;
  }
  
  @media (max-width: ${WINDOW_SIZE.PHONE}px) {
    padding: 0 20px;
  }
`;

const TextContent = styled.div<{ index: number }>`
  display: flex;
  min-width: 240px;
  flex-direction: column;
  font-weight: 500;
  justify-content: center;
  width: 100%;
  padding-right: ${({ index }) => (index % 2 === 0 ? '50px' : '0')};
  padding-left: ${({ index }) => (index % 2 === 0 ? '0' : '50px')};

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    max-width: 100%;
    text-align: center;
    width: unset;
    padding: 0 30px;
  }

  @media (max-width: ${WINDOW_SIZE.PHONE}px) {
    padding: 0 10px;
  }
`;

const CardTitle = styled.h2`
  color: #333;
  font: 48px/1 Gilroy, sans-serif;

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    max-width: 100%;
    font-size: 1.5rem;
    line-height: 1.5rem;
    padding: 0 50px;
  }
  @media (max-width: ${WINDOW_SIZE.PHONE}px) {
    font-size: 30px;
  }
`;

const CardDescription = styled.p`
  color: var(--slate-8-d-8-d-8-d, #8d8d8d);
  margin-top: 20px;
  font: 24px/34px Inter, sans-serif;
  white-space: pre-line;

   @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
     font-size: 1rem;
    line-height: 1.5rem;
    font-weight: 500;
   }

  @media (max-width: ${WINDOW_SIZE.PHONE}px) {
    font-size: 18px;
    line-height: 20px;
  }
`;

const ImageWrapper = styled.div<{ index:  number, hasExtraData: boolean }>`
  display: flex;
  min-width: 240px;
  flex-direction: column;
  overflow: hidden;
  margin: auto 0;
  width: 100%;
  padding-right: ${({ index }) => (index % 2 === 0 ? '0' : '50px')};
  padding-left: ${({ index }) => (index % 2 === 0 ? '50px' : '0')};
  grid-column: ${({ index }) => (index % 2 === 0 ? '2/3' : '1/2')};
  grid-row: ${({ hasExtraData }) => (hasExtraData ? '1/3' : '1/2')};

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    grid-row: 2/3;
    grid-column: unset;
    max-width: 100%;
    width: unset;
    padding: 0;
  }
`;

const CardImage = styled.img`
  aspect-ratio: 1.24;
  object-fit: contain;
  object-position: center;
  width: 100%;
  border-radius: 31px;

  @media (max-width: 991px) {
    max-width: 100%;
  }
`;

export default OfferCard;
