/**
 * This code was generated by Builder.io.
 */
import { MAX_WIDTH_MEDIA_SCREENS } from "@/Themes/Device";
import { DEBIT_CARD_IMG_URL_MAP } from "@/constants/AssetConstants";
import React from "react";
import styled from "styled-components";

const TravelTip: React.FC = () => {
  return (
    <TipWrapper>
      <TipContent>
        <TipIcon
          src={DEBIT_CARD_IMG_URL_MAP.TRUCK_ICON}
          alt="Travel tip icon"
        />
        <TipText>
          <TipTitle>Travelling soon?</TipTitle>
          <TipDescription>
            You can get your Zero Forex Card in 4-10 days!
          </TipDescription>
        </TipText>
      </TipContent>
    </TipWrapper>
  );
};

const TipWrapper = styled.aside`
  border-radius: 16px;
  border: 1px solid var(--Supporting-Jade-100, #a8e0d3);
  background-color: var(--Neutrals-Ivory-50, #f6f9fd);
  display: flex;
  margin-top: 20px;
  min-height: 79px;
  width: calc(100% - 100px);
  flex-direction: column;
  overflow: hidden;
  font-size: 12px;
  color: var(--Content-On-Light-High-Emphasis-850, #313234);
  font-weight: 700;
  line-height: 16px;
  justify-content: center;
  padding: 8px 16px;
  margin: 0 50px;

  @media (${MAX_WIDTH_MEDIA_SCREENS.tab}) {
    gap: 30px;
    width: 100%;
    margin-left: 50px;
  }

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    max-width: 100%;
    margin: 0;
  }
`;

const TipContent = styled.div`
  display: flex;
  min-height: 63px;
  width: 100%;
  align-items: center;
  gap: 12px;
  justify-content: start;

  @media (max-width: 991px) {
    max-width: 100%;
  }
`;

const TipIcon = styled.img`
  aspect-ratio: 1;
  object-fit: contain;
  object-position: center;
  width: 30px;
  align-self: stretch;
  margin: auto 0;
`;

const TipText = styled.div`
  font-feature-settings: "liga" off, "clig" off;
  align-self: stretch;
  flex-grow: 1;
  width: 470px;
  margin: auto 0;

  @media (max-width: 991px) {
    max-width: 100%;
  }
`;

const TipTitle = styled.h4`
  font-size: 16px;
  line-height: 20px;
  margin-bottom: 4px;
  font-family: Inter, sans-serif;

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    font-size: 14px;
    font-weight: 600;
    line-height: 16px;
    text-align: left;
  }
`;

const TipDescription = styled.p`
  font-weight: 400;
  font-size: 16px;
  line-height: 20px;
  color: rgba(49, 50, 52, 1);
  font-family: Inter, sans-serif;

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    font-size: 13px;
    font-weight: 400;
    line-height: 16px;
    text-align: left;
    padding-right: 50px;
  }
`;

export default TravelTip;
