import { NAVIGATION_URLS } from '../../constants/AppConstant';

const GET_APP_ASSISTANCE_DATA = 'app/GET_APP_ASSISTANCE_DATA';
const SET_APP_ASSISTANCE_DATA = 'app/SET_APP_ASSISTANCE_DATA';
const GET_DYNAMIC_CONSUL_DATA = 'app/GET_DYNAMIC_CONSUL_DATA';
const SET_DYNAMIC_CONSUL_DATA = 'app/SET_DYNAMIC_CONSUL_DATA';
const DEBUG_ENABLE_QUERY_PARAM = 'debugKey';

export const APP_KEY = 'appReducer';

export const CONSUL_META_INFO_PATH_NAME = 'meta-info';

export {
    GET_APP_ASSISTANCE_DATA,
    SET_APP_ASSISTANCE_DATA,
    GET_DYNAMIC_CONSUL_DATA,
    SET_DYNAMIC_CONSUL_DATA,
    DEBUG_ENABLE_QUERY_PARAM,
};

export const PATH_MAP = {
    CREDIT_CARD_WAITLIST_SIGNUP: `${NAVIGATION_URLS.CREDIT_CARD_WAITLIST.url}/signup`,
    CREDIT_CARD_WAITLIST_ELIGIBILITY: `${NAVIGATION_URLS.CREDIT_CARD_WAITLIST.url}/eligibility`,
    SALARY_ACCOUNT_B2B: `${NAVIGATION_URLS.SALARY_ACCOUNT.url}/corporate`,
};
