/**
 * This code was generated by Builder.io.
 */
import { MAX_WIDTH_MEDIA_SCREENS } from "@/Themes/Device";
import React from "react";
import styled from "styled-components";

interface TravelFeatureProps {
  icon: string;
  description: string;
}

const CurrenyBenefit: React.FC<TravelFeatureProps> = ({
  icon,
  description,
}) => {
  return (
    <FeatureWrapper>
      <FeatureIconWrapper><FeatureIcon src={icon} alt="" /></FeatureIconWrapper>
      <FeatureDescription>{description}</FeatureDescription>
    </FeatureWrapper>
  );
};

const FeatureWrapper = styled.div`
  display: flex;
  width: 100%;
  align-items: center;
  gap: 21px;
  justify-content: start;
  &:not(:first-child) {
    margin-top: 35px;
  }
  @media (max-width: 991px) {
    max-width: 100%;
  }
`;

const FeatureIconWrapper = styled.div`
  min-width: 64px;
  width: 64px;
  height: 64px;
  background-color: #DCF3EE;
  border-radius: 200%;
  display: flex;
  justify-content: center;
  align-items: center;

  @media (${MAX_WIDTH_MEDIA_SCREENS.tab}) {
    min-width: 48px;
    width: 48px;
    height: 48px;
  }
  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    min-width: 47px;
    width: 47px;
    height: 47px;
  }
`;

const FeatureIcon = styled.img`
  aspect-ratio: 1;
  object-fit: contain;
  object-position: center;
  width: 28px
  @media (${MAX_WIDTH_MEDIA_SCREENS.tab}) {
    width: 20px;
  }
  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    width: 1.2rem;
  }
`;

const FeatureDescription = styled.p`
  font-feature-settings: "liga" off, "clig" off;
  align-self: stretch;
  width: 375px;
  margin: auto 0;

  @media (${MAX_WIDTH_MEDIA_SCREENS.tab}){
      
  }
  
   @media (${MAX_WIDTH_MEDIA_SCREENS.phone}){
       font-size: 1rem;
       line-height: 1.5rem;
   }
`;

export default CurrenyBenefit;
