/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";
import CurrenyBenefit from "./CurrenyBenefit";
import { MAX_WIDTH_MEDIA_SCREENS, WINDOW_SIZE } from "@/Themes/Device";
import { DEBIT_CARD_IMG_URL_MAP } from "@/constants/AssetConstants";

interface CurrenyBenefitsProps {}

const CurrenyBenefits: React.FC<CurrenyBenefitsProps> = () => {
  const features = [
    {
      icon: DEBIT_CARD_IMG_URL_MAP.MONEY_BAG,
      description: "No need to carry foreign or paper currency",
    },
    {
      icon: DEBIT_CARD_IMG_URL_MAP.CROSS,
      description: "No currency loading fee on adding funds",
    },
    {
      icon: DEBIT_CARD_IMG_URL_MAP.TOP_RIGHT_ARROW,
      description: "Earn up to 7.75% interest on your funds",
    },
  ];

  return (
    <CurrenyBenefitsWrapper>
      <CurrenyBenefitsContent>
        <CurrenyBenefitsTitle>
          Just add INR & spend in 180+ countries
        </CurrenyBenefitsTitle>
        <CurrenyBenefitsDescription>
          Carry just your Fi-Federal Debit Card anywhere and you're sorted!
        </CurrenyBenefitsDescription>
      </CurrenyBenefitsContent>
      <CurrenyBenefitList>
        {features.map((feature, index) => (
          <CurrenyBenefit
            key={index}
            icon={feature.icon}
            description={feature.description}
          />
        ))}
      </CurrenyBenefitList>
    </CurrenyBenefitsWrapper>
  );
};

const CurrenyBenefitsWrapper = styled.section`
  display: flex;
  width: 100%;
  max-width: 1130px;
  align-items: center;
  gap: 100px;
  justify-content: space-between;

  @media (${MAX_WIDTH_MEDIA_SCREENS.tab}) {
    gap: 50px;
    max-width: 80%;
  }
  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    max-width: 100%;
    margin: 0 15px;
    padding: 0 30px;
    justify-content: center;
    flex-direction: column;
  }
`;

const CurrenyBenefitsContent = styled.div`
  display: flex;
  min-width: 240px;
  flex-direction: column;
  font-weight: 500;
  justify-content: start;
  width: 550px;
  margin: auto 0;
  padding-right: 20px;

  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    max-width: 100%;
    text-align: center;
    padding-right: 0;
  }
`;

const CurrenyBenefitsTitle = styled.h2`
  color: #333333;
  font: 48px/50px Gilroy, sans-serif;
  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    max-width: 100%;
    font-size: 2rem;
    line-height: 40px;
    font-weight: 600;
  }

  @media (max-width: ${WINDOW_SIZE.PHONE}px) {
    font-size: 30px;
    line-height: 30px;
  }
`;

const CurrenyBenefitsDescription = styled.p`
  color: #8d8d8d;
  margin-top: 20px;
  font: 24px/34px Inter, sans-serif;
  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    max-width: 100%;
    font-family: Inter;
    font-size: 1rem;
    font-weight: 500;
    line-height: 18.6px;
    text-align: center;
    padding: 0;
  }

  @media (max-width: ${WINDOW_SIZE.PHONE}px) {
    font-size: 18px;
  }
`;

const CurrenyBenefitList = styled.div`
  display: flex;
  min-width: 240px;
  flex-direction: column;
  overflow: hidden;
  color: #313234;
  justify-content: center;
  width: 481px;
  margin: auto 0;
  font: 600 24px/32px Gilroy, sans-serif;
  @media (${MAX_WIDTH_MEDIA_SCREENS.phone}) {
    max-width: 100%;
    padding: 0 40px;
  }

  @media (max-width: ${WINDOW_SIZE.PHONE}px) {
    font-size: 18px;
    padding: 0;
  }
`;

export default CurrenyBenefits;
